### ISSUE TITLE
Proccess stops at installing Python requirements

### ISSUE THREAD

**Issue by iwansyahp** [gae-init/gae-init#1011]
I use Ubuntu 18.04

Process stops when I run yarn (specifically when running pip install -q -r requirements.txt). Sometimes process made my computer freeze.

Any idea what is wrong? I installed all the requirements.

**Comment by rbubley** [comment]
Pip can be surprisingly memory-hungry. Are you running out of memory?

**Comment by rbubley** [comment]
You could try running pip with the `--no-cache-dir` option.

**Comment by lipis** [comment]
I also noticed that it takes too long..

**Comment by mdxs** [comment]
I think the problem of #962 still applies, see my [comment ](https://github.com/gae-init/gae-init/issues/962#issuecomment-434061956) showing similar issues as described in this ticket. Therefore, I'm still using Google AppEngine SDK 218 (as for me 219 up to and including 222 didn't work).

**Comment by mdxs** [comment]
The merge of #1015 should resolve this issue and you should be able to use the latest SDK.
