### ISSUE TITLE
freeze when running gulp on new windows 10 machine

### ISSUE THREAD

**Issue by do-n-khanh** [gae-init/gae-init#1052]
I got a new laptop, windows 10.
I install everything said on tutorial http://docs.gae-init.appspot.com/quickstart/
I run gulp, and it just freeze.
Please have a look at the image.
![capture](https://user-images.githubusercontent.com/3012507/50595439-a4fe3900-0ee3-11e9-8047-99003ea69b73.PNG)

**Comment by rbubley** [comment]
Is it still slow the second time you start it (i.e. is whatever is slow, being cached?)

**Comment by do-n-khanh** [comment]
yes, it still slow the second time. I try on Macbook pro , it is very fast.

**Comment by mdxs** [comment]
Insufficient information on what versions you're running and which SDKs (as that might be different between the two environments)... Note that some things might have been fixed already, see #962, #1011 and #1015 and see if that (or a similar situation) applies.

For now, I recommend to close this issue to be closed.  As I think it is very similar to above mentioned issues/tickets and the PR might already have fixed it as well (applied on 17 Nov 2018 to GitHub, you might not have had it integrated on 2 Jan 2019). The reason that your Windows and Mac machines may have showed a difference could be for the same reasons... versions of SDKs could have been different.
