### ISSUE TITLE
May need to specify Python2 in create_virtualenv() method of Run

### ISSUE THREAD

**Issue by mdxs** [gae-init/gae-init#1097]
In my Linux based VM, I may need to specify Python2 in create_virtualenv() method of Run; as otherwise it seems to try using Python3 and then "flask" is not found when doing local "gulp" testing.

I'm not 100% sure why this started to happen, perhaps because Python2 is being deprecated...

**Comment by mdxs** [comment]
And while probably completely unrelated... it seems that we may need to pin requests-oauthlib==1.1.0

**Comment by supern8ent** [comment]
I can confirm the requests-oauthlib issue. I recently had to add these to `requirements.txt`

    oauthlib==2.1.0
    requests-oauthlib==1.1.0

**Comment by rbubley** [comment]
I guess we should create two new issues for this — one to tactically pin these oauth libraries, and the other to fix what is necessary to use the current versions.

**Comment by mdxs** [comment]
With the `oauthlib` and `requests-oauthlib` pinning handled elsewhere, this ticket should just be about the subject of perhaps needing to specify Python2 in create_virtualenv() method of Run.

_(and I note that I made the mistake of mixing the two issues, with the excuse that it was late...)_

**Comment by b-cannon** [comment]
This update seems to be preventing it from running on my Windows 10 system now.  I'm getting an error that says 'The path python2 does not exist'.

**Comment by mdxs** [comment]
@b-cannon: Please note that you're adding a comment to an already closed issue. I only noticed because I started/contributed to this and got a notification. You better create a new Issue ticket (and refer to this one or the PR with the change) for your problem so that other with Windows experience could perhaps contribute.
