### ISSUE TITLE
Current code not compatible with oauthlib v3

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#1098]
Issue separated out from Issue #1097.

Solution proposed by @supern8ent:

> add these to `requirements.txt`:
```
oauthlib==2.1.0
requests-oauthlib==1.1.0
```

**Comment by lipis** [comment]
Fixed in #1099.. right?

**Comment by brubakerjeff** [comment]
I just cloned from master and tried to restore dependencies (Ubuntu 18 Subsystem on Windows) and I appear to still be seeing this issue. Let me know if there is anything missing in my description or if this is a different issue.

git clone https://github.com/gae-init/gae-init.git
pip install -r requirements.txt
....
requests-oauthlib 1.2.0 has requirement oauthlib>=3.0.0, but you'll have oauthlib 2.1.0 which is incompatible.

**Comment by mdxs** [comment]
Hmm, seems https://github.com/gae-init/gae-init/commit/65f9975f8adfc60f282a4e6d1c166e29e8ddaa15 did that...

**Comment by brubakerjeff** [comment]
confirmed,  changing back to requests-oauthlib==1.1.0 removed the error.

**Comment by mdxs** [comment]
Fixed in #1112
