### ISSUE TITLE
flask-oauthlib is deprecated in favour of authlib

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#1100]
The author of `flask-oauthlib` has deprecated it in favour of `Authlib`. <https://github.com/lepture/authlib>

There is  [a migration guide](https://blog.authlib.org/2018/migrate-flask-oauthlib-client-to-authlib).

`Authlib` doesn't currently have a compatible license, but from v0.11 will be released under a BSD license, which would be  compatible.

I suspect that this issue will need to be resolved before we can migrate to later versions of `oauthlib`.

**Comment by lipis** [comment]
What's the status with this one?

**Comment by rbubley** [comment]
I don't currently have time to look into this, but would be happy to see anyone else dive in.

**Comment by lipis** [comment]
@rbubley Maybe you find some time now?

**Comment by lipis** [comment]
#1212
