### ISSUE TITLE
url_for mismatch 

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#1216]
Running locally, and looking at (e.g. Github) on http://localhost:3000/admin/auth/,

it reports that the callback URL should be `//localhost:3000/api/auth/callback/github/`
However in the actual auth code, the URL that gets generated is `http://127.0.0.1:8080/api/auth/callback/github/`

Relevant files seem to be 
`main/templates/admin/bit/github_oauth.html` and `main/auth/auth.py`

I presume this is something obscure about how Flask's `url_for` generated the URLs, but cannot immediately see what.

**Comment by lipis** [comment]
Use `_external=True`, `url_for('foo', _external=True)`

**Comment by lipis** [comment]
and run the code from 8080... 3000 is the Browser Sync plugin.. runs a proxy to gae app.

**Comment by lipis** [comment]
`http://127.0.0.1:8080`
