### ISSUE TITLE
Trouble running gulp for local testing with grpcio in app.yaml

### ISSUE THREAD

**Issue by mdxs** [gae-init/gae-init#1392]
With the introduction of `grpcio` inside `app.yaml` in #1330 it seems that I now get constant:

> ImportError: No module named enum

When trying to run a local `gulp`.

Initially I thought my SDK was not compatible... but with some trial and error it seems to boil down to this addition that seems to cause a problem for me.

**Comment by rbubley** [comment]
What specific gulp command were you running to prompt the error?

**Comment by mdxs** [comment]
Just `gulp`

**Comment by supern8ent** [comment]
Me too.

**Comment by rbubley** [comment]
It works for me, so there must be an environment difference. Is there any more of a traceback to give a clue as to what might be going on?
