### ISSUE TITLE
Requirement for email_validator on local test run not satisfied?

### ISSUE THREAD

**Issue by mdxs** [gae-init/gae-init#1430]
Working in a new virtual machine, obtaining `gae-init` from scratch and just doing the minimal steps to get started... I've now hit a problem with the `gulp` command for a local test run.

Most of it works, but the "Oh no...! Something went wrong :(" page shows, while the log shows:
```
...
  File "lib/wtforms/validators.py", line 332, in __init__
    raise Exception("Install 'email_validator' for email validation support.")
Exception: Install 'email_validator' for email validation support.
INFO     2020-04-24 09:45:34,184 module.py:865] default: "GET /_ah/warmup HTTP/1.1" 500 749
INFO     2020-04-24 09:45:34,192 module.py:865] default: "GET / HTTP/1.1" 500 74
```

**Comment by rbubley** [comment]
Looks like we need to add either

email_validator

Or

wtforms[email]

To requirements.txt

**Comment by mdxs** [comment]
Yeah, seems that adding `wtforms[email]` does the trick.
Will try to see if I can pin it to a specific version and submit a PR for it.

**Comment by rbubley** [comment]
Sorry @mdxs, I already did that. #1431

**Comment by mdxs** [comment]
Sure, no problem; added a note for something that could be added as well to identify the version of `wtforms` being used. No problem if you want the PR to be clean; it could be added in another PR.
