### ISSUE TITLE
Race condition in deploy vs creation of lib.zip

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#1439]
It seems `gulp deploy` can sometimes deploy before lib.zip is created.

Workaround pending a fix is to run `gulp deploy` a second time.

**Comment by mdxs** [comment]
Another workaround is to run `gulp build` before `gulp deploy` (at least once, though I typically use `gulp build && gulp deploy` on Linux to ensure it is done every time).

**Comment by rbubley** [comment]
Made irrelevant by #1595
