### ISSUE TITLE
Inconsistencies in gulpfile task descriptions

### ISSUE THREAD

**Issue by mdxs** [gae-init/gae-init#1445]
Noted inconsistencies in gulpfile task descriptions while working on #1444

**Comment by lipis** [comment]
Not sure if we want them there.. :)

Is there anything else than #1444? or we can close it?

**Comment by mdxs** [comment]
For me #1444 just fixes something that was wrong.

So, this could be closed if you don't want to bother with improving it further. Otherwise, this was a reminder for myself to see what else could be done; in due time.

**Comment by mdxs** [comment]
Hmm, doesn't `gulp help` actually use these descriptions?
In that case, it does make sense to at least get them consistent.
