### ISSUE TITLE
feature request: @login_required and @admin_required methods argument

### ISSUE THREAD

**Issue by joernhees** [gae-init/gae-init#244]
would anyone else find it convenient to have the possibility to specify which methods the standard auth decorators become active for?

I often have the case where it's ok to view (`GET`) a page for everyone but modification (`POST`) requires login or admin...

If someone else finds this interesting i'd rewrite the decorators similarly to django's view function decorators in a backwards compatible way, so you can still use `@login_required` without args, but you could also use `@login_required(methods=['POST'])` to only require a login for `POST` requests.

**Comment by bangive** [comment]
i like it too

**Comment by nazroll** [comment]
+1 

i don't think the use case would be business specific. rewriting the decorators to support args can help us build a more specific use case endpoints.

**Comment by jaxon** [comment]
+1

**Comment by joenorton** [comment]
What's an example of an argument you'd want to pass in? I want to better understand this.

You do know you can utilize variables in your route's inside the decorator, as-is, right? And that won't do the trick?

Here's an example decorator - where I am pulling the 'account_id' from the route and using it in the decorator:
```
def account_required(f):
    def account_decorator(f):
        decorator_order_guard(f, 'auth.account_required')

    @functools.wraps(f)
    def decorated_function(*args, **kws):
        account_id = kws['account_id']
        if current_user_account() == account_id:
            return f(*args, **kws)
        return flask.redirect(flask.url_for('account_list'))
    return decorated_function
```

**Comment by topless** [comment]
Just to add my 3.14 cents here, although kind of late, but just in case anyone stumbles on it. I am using mr. norton's approach looking in the request like 

`if 'my_variable' in kws: do_stuff()`

For handling logic I would suggest to use the `API` section where you can actually decorate the methods you desire. Use `control/` only for server side rendering.

**Comment by lipis** [comment]
I'll pass on this one.. Also @topless idea could work :)
