### ISSUE TITLE
security considerations: email & pw auth

### ISSUE THREAD

**Issue by joernhees** [gae-init/gae-init#247]
our email & pw auth is pretty much [HTTP / HTML form based auth](http://en.wikipedia.org/wiki/HTTP%2BHTML_form-based_authentication). It's a very common technique, but also very very very insecure when used via http as it sends plain text credentials around.

I think we should tighten this up in a couple of ways:
 - [ ] for now we should quickly de-activate email & pw login if we're not on https (https-only decorator?)
 - [ ] redirect relevant auth pages to https (causes problems for "https://version.app.appspot.com", so those URIs need to be rewritten to "https://version-dot-app.appspot.com", but probably still the way to go in general)
 - [ ] preferably in general serve everything via https only (as otherwise those redirects could easily be circumvented by a man in the middle attack as without https the client won't be able to tell if the http was modified during transport), [HSTS](http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) comes to mind... [flask-sslify](https://github.com/kennethreitz/flask-sslify)?

**Comment by lipis** [comment]
https://github.com/gae-init/gae-init/commit/2df0f8369554d4788a18d50cc66bbd9265784d58 :D :dancers: :dancer: 

for the docs and other gae-init examples I will not use the https for now and most likely disable the custom login at least :) These custom versions are a bit outdated.. but will come back to them..!!

**Comment by joernhees** [comment]
:+1: thanks

**Comment by lipis** [comment]
:lock: :dancers:  :closed_lock_with_key:
