### ISSUE TITLE
Remove the SweetAlert

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#269]
Maybe we should remove it after all.. it needs maintenance and bunch of other things, so I think we  were rushed a bit with this one.. WDYT?

**Comment by topless** [comment]
+1 send it where it came from. We should keep the framework as "bare" as possible.

**Comment by nazroll** [comment]
+1

**Comment by bangive** [comment]
+1

**Comment by gmist** [comment]
I added it, but it really is not needed +1
