### ISSUE TITLE
When you start gulp and then kill the task, the dev_servers throws an exception

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#277]
It looks like by using the `Ctrl+C` to kill the `gulp` default task... it looks like the development server is still occupying the `8080` port..

**Comment by lipis** [comment]
https://gist.github.com/lipis/8930f516c1528589762f

**Comment by gmist** [comment]
Strange.. I'm test it on 4 machines (all Mac with zsh/bash) and I not able to reproduce this issue.

**Comment by lipis** [comment]
you probably right.. I'll try to make it reproducible and report back..

**Comment by lipis** [comment]
Can't reproduce it.. thought it was that one :)
