### ISSUE TITLE
Password hashing and unique salt

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#294]
Instead of using a static salt value (the one stored in config.CONFIG_DB.salt - see [why salt reuse is ineffective](https://crackstation.net/hashing-security.htm#ineffective)), the user key, and user signup time for hashing users' passwords, it might be better to generate a single, randomly generated, salt value for each user using the methodology described in [this article](https://crackstation.net/hashing-security.htm#properhashing).

Then, all you'd need is a single `password_salt` property for each user in the datastore and simplify the `password_hash()` function in util.py to something like:
```
def password_hash(password, salt):
  m = hashlib.sha256()
  m.update(password.encode('utf-8'))
  m.update(salt)
  return m.hexdigest()
```

Of course, the `get_user_db_from_email()` function in auth/auth.py would also need to be slightly modified to pull out the password_salt value from the user datastore when checking the submitted password.

Also, when a user is created (or the password updated) a new salt would need to be saved to the user datastore entity. [The article](https://crackstation.net/hashing-security.htm#properhashing) suggests the salt should be at least the length of the hash, so something like this should work when creating/updating a user password:
`password_salt = os.urandom(32)` (length for sha256 from [hash.digest_size](https://docs.python.org/2/library/hashlib.html)).

**Comment by dhstack** [comment]
Documentation for [os.urandom()](https://docs.python.org/2/library/os.html#miscellaneous-functions)

**Comment by joernhees** [comment]
... said this when it was introduced... https://github.com/gae-init/gae-init/pull/201#issuecomment-52425144

IIRC, the rational back then was that the DB key is already added to the global salt and "sort of random". That was liked more than adding another field to the user...

**Comment by lipis** [comment]
It was something among those lines sure.. but the thing is that in the end we are using a *salt* per user.. https://github.com/gae-init/gae-init/blob/master/main/util.py#L219-L220

Agree is not that random as it's essentially the timestamp.. but the milliseconds are pretty random, plus we have the key :)

Even if you know how it's produced it's impossible to guess and if you really really want to.. you can add a random number of milliseconds from this range `[-99999..99999]` to the created date, whenever you actually need to reset something, on top of just reseting the general salt which is also included regardless of the solution just to make sure that with one move you can *force* the users to reset their passwords without updating the *salts* per user..

Practically two users with the same password will have different hash and if in any way the database will be leaked or something in both scenarios the salt or creation date or the general salt will be compromised too...

So I'm not convinced that is going to make it *more* secure than is already is.. in practice there is no much difference..

**Comment by dhstack** [comment]
@lipis I would agree that for practical *security* purposes, the current implementation is probably fine.

However, the reason I bring this up is for better *integration* with 3rd party services. I'm trying to integrate with [FoxyCart](https://wiki.foxycart.com/v/2.0/customers#synchronizing_users_and_passwords), and need a *user specific salt* in addition to the password hash to do this securely. The problem right now is there are essentially 3 different salts in gae-init (user creation date, user db key, and config db salt).

I was planning on implementing a single, randomly generated and user specific, salt just for my site, but thought that if other users of gae-init wanted to integrate with another service, they would also require a single salt for all to go smoothly. To be the most secure, the single salt would need to be user specific, and updated every time a user changed their password. That's why I brought up this issue.

**Comment by dhstack** [comment]
I created a pull request if you want to see what I came up with: #297

**Comment by lipis** [comment]
I have to admit that I'm bit confused with the whole FoxyCart integration but no matter what to me it looks like a specific case and if there is any other integration, I'm sure they will be using something else and you will have to readjust.. My point is that we can't please them all and I don't see any point of changing the whole thing because of that. Having one general salt that can easily force to reset all passwords is quite interesting and could be potentially useful, and in short having both is better than having only one.. makes it even more salty I would say :D

So I will pass on this one as more interesting things coming this week that will break bunch of backwards compatibility :) #202, #289

**Comment by dhstack** [comment]
@lipis I should have been more clear. The FoxyCart integration itself doesn't need a per user salt, but the ability to [synchronize passwords](https://wiki.foxycart.com/v/2.0/customers#synchronizing_users_and_passwords) and have a Single Sign On (SSO) do. In order to securely synchronize the passwords with their system (and I would assume other systems), the password hash needs to be sent in addition to a user specific password salt. The other way to do it would be to send clear text passwords, but that is incredibly insecure.

You bring up a good point about having one general salt, and I see its usefulness in resetting all users passwords in one easy step. I've added that functionality back into my PR while also saving the per user salt for easier 3rd party password synchronizations.

So I guess the only thing I'm really changing is the ability to save a per user salt (and how it's generated). The per user salt makes synchronizing passwords with 3rd parties much easier.

**Comment by lipis** [comment]
Actually (if I understood correctly what FoxyCart wants from you) is basically the salt for every user.. that usually used as `hash_function(password + salt)` so all you have to do actually is to introduce a salt function that is based on a `user_db`:

```python
def user_salt(user_db):
  m = hashlib.sha256()
  m.update(user_db.key.urlsafe())
  m.update(user_db.created.isoformat())
  m.update(m.hexdigest())
  m.update(config.CONFIG_DB.salt)
  return m.hexdigest()
```

and then update the current `password_salt` to something like this:

```python
def password_hash(user_db, password):
  m = hashlib.sha256()
  m.update(password.encode('utf-8'))
  m.update(user_salt(user_db))
  return m.hexdigest()
```

Now whenever FoxyCart needs a specific salt for a `user_db` you can offer the `user_salt(user_db)`.. If you think that this is a work around (at least is a pretty secure one) you can always add the `salt` property to the `User` and make it work :) as seen in #295 and even simpler..

**Comment by dhstack** [comment]
@lipis I really liked your suggestion and updated the PR to reflect it. It is much cleaner this way.

I left in the random per user salt because without it, the salt would remain the same even if the user reset their password. This is not as secure as having the salt change every time the user's password changes. A salt shouldn't ever be reused.

>The main and only point of the salt is to be as unique as possible. Whenever a salt value is reused anywhere, this has the potential to help the attacker.

>...

>The cheap way to obtain uniqueness is to use randomness. If you generate your salt as a sequence of random bytes from the cryptographically secure PRNG that your operating system offers (/dev/urandom, CryptGenRandom()...) then you will get salt values which will be "unique with a sufficiently high probability". 16 bytes are enough so that you will never see a salt collision in your life, which is overkill but simple enough.

(From Salt Generation section in this [stackexchange answer](https://security.stackexchange.com/questions/211/how-to-securely-hash-passwords)).

Honestly, in the end, it may just be better to use [bcrypt](https://en.wikipedia.org/wiki/Bcrypt).
