### ISSUE TITLE
The run and watch tasks are running in parallel and resulting in double requests the first time

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#298]
![screen shot 2015-02-06 at 13 12 14](https://cloud.githubusercontent.com/assets/125676/6079164/db4b5b4c-ae01-11e4-8ba6-96d4e370f037.png)

That's a weird one but here it is, check for a new version happens only once per 24 hours (the actual request to the server) and checking that from the date modified of a temp last updated file.. because the two tasks run almost simultaneously there is no time for the request to respond before the second task is doing the same :)

not sure how to resolve that atm.. but just wanted to have it here as an issue for ideas

**Comment by lipis** [comment]
Maybe we could use that https://www.npmjs.com/package/run-sequence as found from https://github.com/gulpjs/gulp/issues/96#issuecomment-33519445

**Comment by joernhees** [comment]
you could touch the file in https://github.com/gae-init/gae-init/blob/master/run.py#L408 already, which would probably mitigate this problem (it makes it much much rarer, but it won't be able to completely solve the race-condition)

**Comment by lipis** [comment]
Yes.. might try touching it there..

**Comment by lipis** [comment]
https://github.com/gae-init/gae-init/commit/c91c547076f0ec7c4f4214c0c95819dde1aa1d48
