### ISSUE TITLE
dev_appserver.py is not included when installing the latest gcloud on a new machine

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#313]
I installed the SDK yesterday on a new machine and realised that the `dev_appserver.py` is not included..  https://cloud.google.com/sdk/

We should start using `gcloud ...` commands to run the server and check if app engine is installed.

**Comment by gmist** [comment]
```gcloud components update gae-python```?

**Comment by lipis** [comment]
Right.. the computer left the building, and it's not installed by default as it used to do (if I'm not mistaken).. all there :)
