### ISSUE TITLE
Where is the ext/ directory?

### ISSUE THREAD

**Issue by Stubbs** [gae-init/gae-init#315]
When I run the dev server with ./run.py I get the following error:

    [09:13:35]    NOT FOUND main/static/ext/bootstrap/js/alert.js

along with other files in the ext/ directory. Do I need to install ext separately?

**Comment by gmist** [comment]
try to run ```./run.py -C```

**Comment by lipis** [comment]
Yes.. it looks like something went wrong with the initial bower installations.. `./run.py -C` usually fixes all of the issues :)

**Comment by Stubbs** [comment]
Ok, making some progress now, I was missing less, but now I'm getting:

    FileError: '../../ext/font-awesome/less/font-awesome.less' wasn't found. Tried - /Users/stu/Projects/er/main/static/ext/font-awesome/less/font-awesome.less,/Users/stu/Projects/er/main/static/ext/font-awesome/less/font-awesome.less,../../ext/font-awesome/less/font-awesome.less in /Users/stu/Projects/er/main/static/src/style/style.less o

**Comment by lipis** [comment]
maybe you're getting some other errors during installation.. can you post the complete output after running the `./run.py -C` until it stops?

**Comment by Stubbs** [comment]
Hang on, that's un upper case 'C' isn't it ... problem solved!
