### ISSUE TITLE
What's the recommended way of integrated gae-init-upload?

### ISSUE THREAD

**Issue by pigeonflight** [gae-init/gae-init#316]
I've started a project using gaeinit and now want to add upload functionality. What's the recommended way to do this?
Also, I wasn't sure where to post this question, hence the reason I'm using the bugtracker.

**Comment by lipis** [comment]
The recommended and the easiest (and maybe the only way) is to do the following:

```shell
git pull https://github.com/gae-init/gae-init-upload.git master
```

But if you changed bunch of things you might have issues with the merge..

**Comment by lipis** [comment]
Before doing the above though, make sure you are a bit familiar with the `gae-init-upload` and make sure you are working on a new branch to avoid broken stuff..

**Comment by lipis** [comment]
One more thing.. The above is going to be smooth only if you are up to date with `gae-init`.. if you're not then I suggest you to upgrade to `2.1.0` before trying merging the upload.. if you are not on version 2, I would recommend not even trying to merge with upload..

**Comment by pigeonflight** [comment]
It worked. But was not smooth. I had to fix merge conflicts in more than 10 files. It seems that I would have been better off doing the pull at the beginning of my project and not later on. It could simply be inexperience, but it feels like there needs to be a better way to plug these things in, but I don't know enough about Flask yet to make a sensible suggestion.

**Comment by lipis** [comment]
next time if you want to start a project with uploading.. simply fork from gae-init-upload  and keep merging from gae-init or wait until it will be synced and you are golden..

**Comment by pigeonflight** [comment]
What if I wanted to use upload and babel?

**Comment by lipis** [comment]
:D maybe starting from babel and then merging with upload.. as babel is a bit more intrusive :) I see your point.. but if you know these things from the beginning the merges are smooth no matter what you choose.. they are all having the same parent and I'm trying to keep them as much in sync as possible.. the earlier the better and then just keep getting the updates from the one that you started or gae-init...

**Comment by pigeonflight** [comment]
I get the concept. This, of course, will require more forward planning and assumes more familiarity with the gae-init stack than a beginner might possess. For the project I'm working on now, I can afford to back track as it's less than 2 days of customizations.

But I can see this being painful for a newbie that has spent 2 weeks working on stuff and then suddenly realizes that they need babel and upload.

**Comment by lipis** [comment]
Yes, unfortunately that's the case and doing anything more complicated at the moment it requires some knowledge. Even though starting the project is super easy even for newbies, customizing it requires you know a bit deeper knowledge of the stack in general: App Engine, Flask, Storage, Babel just to begin with.. I would say that to get all the benefits of this project you have to be a bit more experienced web developer. Having said that though if you take one step at the time is still very easy. Plus for a newbie to start a multilingual website is a huge task anyway to make it right :)

**Comment by pigeonflight** [comment]
Gae-init is fantastic for developers who know web dev but need to bootstrap a Flask/Appengine project. It certainly allowed me to get some key things started quickly. For that it is fantastic. 

I'd like to see future versions make the extensions more "pluggable" this would be the "magic" that would make it more newbie friendly. Since I'm not ready to scratch that itch, open source etiquette requires that I just say thanks for what you've done so far and shut up for now :).

**Comment by lipis** [comment]
Don't shut up.. keep your comments coming :) Check your email regarding _magic_ :dancer:
