### ISSUE TITLE
ImportError: No module named docker

### ISSUE THREAD

**Issue by dabcoder** [gae-init/gae-init#318]
This is the gist: https://gist.github.com/dabcoder/f70604bac69fd48c7147

So I am getting the above error when running `./run.py -s` but when running `dev_appserver.py main` everything is smooth. 

Any ideas? Thanks in advance.

**Comment by gmist** [comment]
Just remove ```vm: true``` form your ```app.yaml``` file.

**Comment by dabcoder** [comment]
Here's my app.yaml file: https://github.com/dabcoder/gae-init/blob/master/main/app.yaml

Can't seem to see a vm: true there

**Comment by gmist** [comment]
Hmm... interesting... I got the same error after updating google-cloud-sdk to the latest version.

**Comment by lipis** [comment]
But it works with the `dev_appserver.py main`? @gmist we might have to start using the new commands in general.. :)

**Comment by gmist** [comment]
In ```run.py``` we using ```dev_appserver.py``` form ```<path>/google-cloud-sdk/platform/google_appengine/``` but in the latest version of google-cloud-sdk we should use ```<path>/google-cloud-sdk/bin/dev_appserver.py```.

**Comment by gmist** [comment]
Just remove line 493 from your ```run.py``` file and it should work
``` python
  gae_path = os.path.join(gae_path, '..', 'platform', 'google_appengine')
```

**Comment by lipis** [comment]
@gmist shall we remove it and make a release with a note to upgrade to latest? do you want to make a PR?
