### ISSUE TITLE
GitHub login doesn't work

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#325]

**Comment by gmist** [comment]
Hmm... it works for me
https://my-gae-init.appspot.com/signin/

**Comment by lipis** [comment]
In the settings of github replaces `https` with `http` and it worked.. :(

**Comment by lipis** [comment]
can you verify if you have https in your settings?

**Comment by gmist** [comment]
Strange, but it really does not work...

**Comment by gmist** [comment]
GitHub returns ```redirect-uri-mismatch``` error.

**Comment by gmist** [comment]
194.48.218.78 - serg.baburin [05/Mar/2015:03:44:26 -0800] "GET /_s/callback/github/oauth-authorized/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch HTTP/1.1" 302 723 - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18" "my-gae-init.appspot.com" ms=156 cpu_ms=0 cpm_usd=0.000081 instance=00c61b117cd56631963bcef2fc96508e0d7d33 app_engine_release=1.9.18
