### ISSUE TITLE
Task security risk?

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#329]
Doesn't app.yaml need this to prevent anyone from executing the tasks (email, etc.)?
```
- url: /_ah/queue/deferred
    script: google.appengine.ext.deferred.deferred.application
    login: admin
```

Source: https://cloud.google.com/appengine/articles/deferred

**Comment by lipis** [comment]
hmm.. might overlooked that one and never came back to it..

**Comment by lipis** [comment]
I was about to add it.. but it looks like this URL is already forbidden by default for non-admins
https://gae-init.appspot.com/_ah/queue/deferred

(First one without being an admin and the second one when admin)
![screen shot 2015-03-16 at 02 05 28](https://cloud.githubusercontent.com/assets/125676/6659230/095ddf04-cb81-11e4-8bb7-a554bffc2e6b.png)

**Comment by lipis** [comment]
I submitted an issue regarding the documentation.. and they will update it :) so let's see.. practically we are safe without it..

**Comment by dhstack** [comment]
good to know, thanks for looking into this
