### ISSUE TITLE
Unable to install google-api-python-client using run.py

### ISSUE THREAD

**Issue by nazroll** [gae-init/gae-init#338]
I was trying to install google-api-python-client.

My steps:
* Edit requirements.txt
* Added in google-api-python-client in the next line.
* Execute ``run.py -C``.

This error appears:
![screen shot 2015-03-31 at 2 44 25 pm](https://cloud.githubusercontent.com/assets/33108/6913564/8f47002a-d7b4-11e4-99fb-1049dd55ecea.png)

**Comment by gmist** [comment]
@nazroll please try [this PR](https://github.com/gae-init/gae-init/pull/339)

**Comment by nazroll** [comment]
@gmist it works. thank you
