### ISSUE TITLE
Login/Signup Form

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#344]
I have just setup a local version of gae-init, and when I run the website at http://127.0.0.1:8080, both the signup form (http://127.0.0.1:8080/signup) and the signin form (http://127.0.0.1:8080/signin) look like the following:
![clip_2](https://cloud.githubusercontent.com/assets/6990981/7349145/f6a94c92-ecee-11e4-8f8d-0ade9bdf8fd1.png)

What is going on here? I am trying to get it to look like the respective forms at https://gae-init.appspot.com/signin/ and https://gae-init.appspot.com/signup/

Thanks!

**Comment by lipis** [comment]
It's not that obvious but since these forms require from the app to send an email you will have to have the feedback email filled in... Locally it doesn't matter which one, but on production it should be one of the admins of the app.

**Comment by lipis** [comment]
https://cloud.google.com/appengine/docs/python/mail/sendingmail check the bullet points..

**Comment by charleswson** [comment]
Hi Lipis

I have filled out the Feedback email in the Admin panel, and I seem to have fulfilled all of the bullet points in the link above. Whenever I click Sign In, the following page is displayed, rather than the sign in form I was expecting:

![clip_3](https://cloud.githubusercontent.com/assets/6990981/7352317/b189653e-ed02-11e4-9540-7126d0d2e5bd.png)

Whenever I try to display /signup, the Sign In form is still displayed

**Comment by lipis** [comment]
this blue page will appear only locally when you are clicking on Sign in with Google.. so you will have to login as admin (locally any email will do as long as you have the checkbox selected) and the by going to http://localhost:8080/admin/config/ updating the right things to have the Email authentication on..

![screen shot 2015-04-27 at 19 35 13](https://cloud.githubusercontent.com/assets/125676/7353537/9f2db84c-ed14-11e4-8818-a394abafdabf.png)

**Comment by charleswson** [comment]
Hi Lipis

Thank you very much! The problem I was having was that the "Email authentication for sign in/sign up" checkbox wasn't checked, so the only login option appearing was the Google+ login button. 

Thank you once again!
