### ISSUE TITLE
Running gae-init 3.0.0

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#354]
When trying to run the latest version of gae-init (3.0.0) by running gulp in the Terminal, I receive the following error:

![clip_2](https://cloud.githubusercontent.com/assets/6990981/7455616/c7764470-f275-11e4-98e9-7348c50876b2.png)

What is the issue here? 

Thanks!

**Comment by lipis** [comment]
did you start from scratch or wanted to upgrade something?

```
npm install 
gulp
```

or if your `gulp` is broken (usually after an upgrade) I'm doing the following... :)

```
npm install
gulp reset
npm install
gulp 
```

**Comment by charleswson** [comment]
Yes, that worked! Thank you very much for your quick response :)

**Comment by lipis** [comment]
Because most likely you had some outdated stuff.. with v3 you have to reset everything :D
