### ISSUE TITLE
Some feedback and thoughs about the new `gulp deploy` task

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#358]
1. The current `gulp deploy` is nice that is rebuilding everything from scratch, but it's taking too much time when you are doing that many times per day. Suggestion: maybe we should have another task like `gulp deploy-fast` which will not `clean:venv` (or have the `gulp deploy-clean` that will do that and the current one will be the fast one)

2. When I'm running the default task ATM and I want to deploy something, I'm doing it from another terminal window so I don't have to kill the current task. The problem is that after the deployment since the `clean` task was performed all the dev static files are gone so we have to rerun the default task or make a change in one of the static files. Suggestion: Removing the [`['clean:dev']`](https://github.com/gae-init/gae-init/blob/master/gulp/tasks/clean.coffee#L8) from the `clean` task.

**Comment by lipis** [comment]
Even though something is still not right.. I'll open another task..

**Comment by bangive** [comment]
i don't know how to minify before deploying, please show me how.

**Comment by lipis** [comment]
`gulp deploy` does everything for you

**Comment by bangive** [comment]
but when i excute this code it does not produce lib.zip as before

**Comment by lipis** [comment]
it produces on my side :)

**Comment by gmist** [comment]
" it does not produce lib.zip"
It's very strange... are there any errors in the terminal?

**Comment by bangive** [comment]
ok, i've get it right. Thank you.

**Comment by lipis** [comment]
just get the latest changes from `gae-init` and it's not going to do that anymore..

**Comment by lipis** [comment]
@bangive #390
