### ISSUE TITLE
Missing python libs

### ISSUE THREAD

**Issue by wilfriedE** [gae-init/gae-init#361]
After Resetting the project the python libs seemed to be missing.  
This is what I get when I run ```gulp```
```
Traceback (most recent call last):                                                                             
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\w
sgi.py", line 240, in Handle                                                                                   
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())                                          
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\w
sgi.py", line 299, in _LoadHandler                                                                             
    handler, path, err = LoadObject(self._handler)                                                             
  File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\w
sgi.py", line 85, in LoadObject                                                                                
    obj = __import__(path[0])                                                                                  
  File "C:\Users\~\GAE-INIT\main\main.py", line 3, in <module>                                
    import flask                                                                                               
ImportError: No module named flask```

**Comment by gmist** [comment]
How do you reset the project? via ```gulp reset```?

**Comment by wilfriedE** [comment]
yeah, then I did ```npm install``` followed by ```gulp``` .

**Comment by gmist** [comment]
It's strange ... try running:
``` shell
gulp clean:venv
gulp
```

**Comment by lipis** [comment]
Are you sure you don't have any other errors during the initial `gulp`? Sometimes if the internet is not OK or a timeout some of the installations might fail, but the process will finish.

**Comment by lipis** [comment]
Any like @wilfriedE?

**Comment by wilfriedE** [comment]
Running 
```
gulp clean:venv 
gulp 
```
 didn't help it. I got this message when running ```gulp``` 
``` \Google\google_appengine\"" was unexpected at this time.```
And what's the best way to test if internet is ok. I am guessing it would tell me but not sure.

**Comment by wilfriedE** [comment]
Internet is ok as well. And I was thinking that here: https://github.com/gae-init/gae-init/blob/master/run.py#L267 there should be a print out if Internet is not Ok.

**Comment by lipis** [comment]
It will eventually that the Internet is not OK, if you follow the `internet_on` and ultimately ending up here: https://github.com/gae-init/gae-init/blob/master/run.py#L274

**Comment by gmist** [comment]
What is displayed when you run
```
./run.py -d
```
?

**Comment by wilfriedE** [comment]
@lipis :+1: 
@gmist  I switched machines to see if it changes anything. I made sure to reset before run. This is what I get when I run ```.\run.py -d```

```
\Google\google_appengine\";C:\Program Files\Java\jdk1.8.0_25\bin;" was unexpected at this time.
\Google\google_appengine\";C:\Program Files\Java\jdk1.8.0_25\bin;" was unexpected at this time.
```
And just in case, this is what I get on the other machine.
```
\Google\google_appengine\" was unexpected at this time.
\Google\google_appengine\" was unexpected at this time.
```

**Comment by gmist** [comment]
Hmm... It looks like a problem with the environment variables... what is displayed when you run
``` shell
echo %PATH%
```
?

**Comment by wilfriedE** [comment]
Thanks @lipis and @gmist for the help :+1: . It was an issue with the path. I used to have quotation around some of the paths to handle the space issue on windows. Removing the quotations seems to have helped. :rocket:
