### ISSUE TITLE
Website Styling

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#362]
Hi!

I am trying to change the style of different elements on the website, on top of Bootstrap. For the most part, this appears to be very straightforward (especially with Gulp), simply amending or adding any Less files. However, I cannot see how it is possible to customize the appearance of form elements, which are created using Flask-WTF in the HTML.

I am specifically looking at integrating this package (http://www.creative-tim.com/product/get-shit-done-pro)

Additionally, where would I place any additional Javascript files, and which path would I use to access them?

Many thanks!

**Comment by lipis** [comment]
Your starting point should be here: https://github.com/gae-init/gae-init/blob/master/main/templates/macro/forms.html if you are using any of the `{{forms....}}` in your templates and start figuring out the clues :)

If you are just modifying the Bootstrap styles, I would recommend you to simply override change their style according to Bootstrap's guidelines and of course checking the exact dom structure http://getbootstrap.com/css/#forms

**Comment by charleswson** [comment]
Thank you very much! Somehow I had missed forms.html when looking through the codebase

**Comment by lipis** [comment]
Good luck :)

**Comment by lipis** [comment]
Also take a look on this PR, on how you could integrate something that was already done by somebody else https://github.com/gae-init/gae-init/pull/360

**Comment by charleswson** [comment]
Doesn't that require the package to be a bower dependency?

**Comment by lipis** [comment]
Yep: https://github.com/gae-init/gae-init/pull/360/files#diff-0a08a7565aba4405282251491979bb6b

**Comment by charleswson** [comment]
Is that allowed if it is a product which I paid for?

**Comment by lipis** [comment]
You just have to comply with all their licenses.. and you should be good to go..

**Comment by charleswson** [comment]
So registering it as a bower package doesn't make it available publicly through Bower?

**Comment by charleswson** [comment]
Am I right in thinking that I have to create another Github repository to import the files using Bower then?

**Comment by lipis** [comment]
Just check what I changed in #360 and try it on your local instance.. there is nothing you need to create on GitHub

**Comment by charleswson** [comment]
But from my understanding, Bower recognizes what Bootswatch is so it is able to import it to /bower_components. But my package isn't a Bower package, so what is the best way of using it in my project?

**Comment by gmist** [comment]
I would just copied it to ```main/static/src```, added styles in ```main/static/src/style/style.less``` and scripts paths in ```gulp/config.coffee```.

**Comment by charleswson** [comment]
Okay, thanks @gmist ! So at which path should the .js files be placed?

**Comment by gmist** [comment]
In any place most convenient to you. For example, we have the following directory structure
```
main/static/src/my_cool_theme/style/theme.css
main/static/src/my_cool_theme/js/script.js
```

Now plug it to the project:
1. Add line ```@import (css) "../../my_cool_theme/theme.css";``` in ```main/static/src/style/style.less```.
2. Add line ```"#{paths.static.root}/my_cool_theme/js/script.js" ``` in ```ext``` section into  ```gulp/config.coffee```.

**Comment by charleswson** [comment]
Thank you both so much! I really appreciate it, and would be happy to help in any way I can! :)
