### ISSUE TITLE
Linked in sign in invalid redirect_uri.

### ISSUE THREAD

**Issue by topless** [gae-init/gae-init#363]
When I am trying to sign in with linked in.

![screenshot 2015-05-13 09 07 44](https://cloud.githubusercontent.com/assets/230805/7605424/99a7f3be-f94f-11e4-927d-a86cb35de880.png)

**Comment by lipis** [comment]
Did you restart the instance?

**Comment by lipis** [comment]
It doesn't work here as well: https://gae-init.appspot.com/signin/

**Comment by topless** [comment]
Thats where I was referring too, forgot to mention it.

**Comment by lipis** [comment]
Fixed..
