### ISSUE TITLE
missing client_id in authentication request (google+)

### ISSUE THREAD

**Issue by peter-kolenic** [gae-init/gae-init#364]
i am trying to deploy b3f2d92c09500540e9c97887321393b325b59719 on appengine, and i am unable to make authentication work - i either get 
> error "sequence index must be integer, not 'str'"

in logs, or

>  Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

in the browser, depending on the way i try to do initial setup of app. 
Might be the reason the way of my initial setup  ?
For the case, i described it in 
https://gist.github.com/peter-kolenic/91799b1a8237481c0ff9

Should "appengine -> app settings -> Authentication Type" be set to federated login, or google accounts api ? 
Should be something manually set in app engine datastore viewer, in config entity, just after deploy - before trying to do first login ?

thanks a lot

**Comment by lipis** [comment]
Did you restart the instances?

![screen shot 2015-05-14 at 07 55 19](https://cloud.githubusercontent.com/assets/125676/7626775/a720caec-fa0e-11e4-84d1-9730e72331d9.png)

**Comment by peter-kolenic** [comment]
no, i did not.
Thanks a lot, now i see it big and clear.
After restarting, everything works.

**Comment by lipis** [comment]
nobody sees that actually.. maybe it make more sense to flash it after save..

**Comment by peter-kolenic** [comment]
when i think about why i overlooked it, it seems to me that the reason might have more to do with me setting Authentication Type in Application settings to "Federated Login" on app creation, being somehow able to Sign in at least once (maybe during the night app engine shut down my inactive instance or something), and thus learning (erroneously), that initial conf should be done with direct Datastore Config manipulation. Then, when seeing "Auth Config", i would never read the note about restarting - i thought it just updates Config. I was completely stuck (updating node, pip, gae tools, trying with last ubuntu, ...).
So i am very very thankful for Your help.

I have tried today to set gae-init up with federated login set, as here:
  https://gist.github.com/peter-kolenic/9db326f3c14e06a15586

So i suggest, that in README.md, sentence:

> Before deploying make sure that the main/app.yaml and gulp/config.coffee are up to date.

be changed to:

> Before deploying make sure that the main/app.yaml and gulp/config.coffee are up to date, and
>  Authentication Type in App Engine console is set to "Google Accounts API".
