### ISSUE TITLE
Local server not running

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#368]
I am getting the following error messages in my Terminal.

![clip_1](https://cloud.githubusercontent.com/assets/6990981/7667474/64947652-fc01-11e4-8be2-56b0aac209a4.png)

What might be causing this?

Many thanks!

**Comment by lipis** [comment]
I'm getting that a lot as well after switching to `gulp`. The GAE instance is still running so you will have to kill them manually or run it using another port ( example: `gulp -p 3333`)

You could kill them all with the following.. but I have to admin that many times this is not working :/ and I have to do it, either by finding the id or through the activity monitor (on OSX)
```
killall Python
```

**Comment by charleswson** [comment]
Thanks @lipis! I tried running it through another port and that seems to work for now!

**Comment by lipis** [comment]
The thing is that the livereload might not work as well..

**Comment by charleswson** [comment]
Okay! Is there a particular reason for that?

**Comment by lipis** [comment]
It has to do with gulp and when you are killing the task, it looks like gae is still running in the background.. not sure how to resolve that.. any idea is welcome :)

**Comment by lipis** [comment]
@gmist have you experienced that?

**Comment by gmist** [comment]
At me it happens very very rarely, so I just do not worried about it. Now I think about docker containers for isolating runtime environment.

``` shell
GAE_CONTAINER=`docker run -p 8080:8080 -v /Users/serg/Develop/appengine/my-gae-init/:/project --rm -ti --volumes-from gcloud-gae-init google/cloud-sdk sh -c "cd /project && gulp"`
...
docker kill GAE_CONTAINER
```
but it will not be easy for Windows users.

**Comment by charleswson** [comment]
I tested it using 2.5.0 and the same error message is still appearing?

**Comment by charleswson** [comment]
This seems to be happening most of the time for me now. Does anyone have any idea what might be causing this?

**Comment by charleswson** [comment]
I ran 

      gcloud components update

and that seemed to stop this issue from occurring. Does this work for other people as well?

**Comment by charleswson** [comment]
I've found that this seems to kill the port reliably:

    lsof -P | grep ':8080' | awk '{print $2}' | xargs kill -9

**Comment by lipis** [comment]
I think I will close that for now..
