### ISSUE TITLE
Add WrapBootstrap Support

### ISSUE THREAD

**Issue by jaxon** [gae-init/gae-init#370]
I am working on integrating a WrapBootstrap theme (The Project) into gae-init. 

I don't know if WrapBootstrap themes follow a standardized structure or not -- like Bootswatch does -- but if they do, I think WrapBootstrap support would be a great feature for gae-init.

In the mean time, I am going to use the Bootswatch example as a starting point:

https://github.com/gae-init/gae-init/pull/360/files

**Comment by lipis** [comment]
They don't.. they are all different and there is no way to get them automatic..

**Comment by jaxon** [comment]
Boo to the Wrapbootstrap folks for not adopting a standard. 

I was able to make it work by turning the theme's download into a private bower.
