### ISSUE TITLE
How to sign in, sign up, save login, REST on android

### ISSUE THREAD

**Issue by bangive** [gae-init/gae-init#374]
I am developing an android app. In the app i want to sign in, sign up user. User can save login.
User use REST to do things like get, create, delete... If user not logged in user will not allowed to use REST.

Could you show me how to do that
Thank you very much.

**Comment by jaxon** [comment]
+1

**Comment by lipis** [comment]
That is one way.. https://github.com/gae-init/gae-init/pull/428

**Comment by lipis** [comment]
#428 is already merged..
