### ISSUE TITLE
Signup with password and other fields before activated.

### ISSUE THREAD

**Issue by bangive** [gae-init/gae-init#375]
In the Signup page, i'd like to add password field and other fields but the default is only email field.
How to do that. Thank you

**Comment by lipis** [comment]
Unfortunately you will have to do that yourself and doing exactly that.. adding the fields that you want and using them. But I would recommend before doing that, you should get more familiar with the whole structure and how the different components are working together, and eventually it will be much easier for you.. if you actually going to need that :)
