### ISSUE TITLE
Is Flask-bcrypt, Flask-scrypt is good to store password

### ISSUE THREAD

**Issue by bangive** [gae-init/gae-init#376]
I've just read this article https://patrickmn.com/security/storing-passwords-securely/. It said that its better to use bcrypt or scrypt instead of hashlib.

**Comment by lipis** [comment]
I might change this in the future and use some of the ideas describing in this article
http://blog.codinghorror.com/your-password-is-too-damn-short/

but not at the moment.. we'll make it more _secure_ later.
