### ISSUE TITLE
How to upgrade an NDB model

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#380]
From my understanding, it is currently quite difficult to upgrade the schema of a model once it is already being used. Is that correct?

I asked this question on StackOverflow (http://stackoverflow.com/questions/30424506/updating-an-ndbs-models-schema/) but am not sure whether I am asking the correct question. Is this possible with gae-init?

Many thanks!

**Comment by lipis** [comment]
It really depends on the how much data you have and what exactly you want to upgrade.

- [Expando](https://cloud.google.com/appengine/docs/python/ndb/entities#expando) is your friend.

- You can get some ideas from the [Updating your model's schema](https://cloud.google.com/appengine/articles/update_schema) that was written for `db` but more or less same principles apply for `ndb`. There you will find references to `deferred` libraries and more..

**Comment by charleswson** [comment]
Thank you lipis! Is there a way to automate this process, so that it can be applied to any models which are updated in the future?

**Comment by lipis** [comment]
I would recommend you to do it the way you think doing it the first time.. and every time you need to upgrade take the old code and improve it.. because like I mentioned before.. there are very different kind of model upgrades...

**Comment by charleswson** [comment]
Okay - thank you very much!
