### ISSUE TITLE
Leveraging browser caching

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#382]
Looks like the expiration parameter(s) for static files in app.yaml [needs to be a string](https://cloud.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Static_directory_handlers). Right now it is just an integer.

Should also be a maximum of 365 days. From Google PageSpeed Insights:
"We recommend a minimum cache time of one week and preferably up to one year for static assets, or assets that change infrequently."
https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

I think the minimum should be 1 week. 1 month could also work. As most people using gae-init are still in the process of developing, a 1 week default would be better given the many changes to a site during development.

**Comment by lipis** [comment]
You have some good points here.. for js/css we have to have it cache forever.. maybe 365d as we are using the [version number as a URL argument](https://github.com/gae-init/gae-init/blob/master/main/templates/bit/script.html).. so it will be cached normally..

**Comment by dhstack** [comment]
Aren't some resources not always cached by some proxy caching servers when using URL arguments?

Still learning about caching...why do we need to cache js/css forever?

**Comment by mdxs** [comment]
It is not just an integer at the moment... it is `1000d` which seems to be interpreted as `"365d"` when I look at in Chrome, F12, Network, All view: select a static resource and inspect the `max-age` in the `cache-control` header and the `expires` header itself (compared to the `date` header). However, it would be best to be explicit about this in the app.yaml
