### ISSUE TITLE
run.py -w unrecognized argument

### ISSUE THREAD

**Issue by bangive** [gae-init/gae-init#385]
I changed locale.less file. Then excute run.py -w and i get the following error:
E:\Projects\gae-init>run.py -w
usage: run.py [-h] [-d] [-s] [-o HOST] [-p PORT] [--appserver-args ...] [-v]
              [-i] [-u] [-l PYBABEL_LOCALE]
run.py: error: unrecognized arguments: -w

**Comment by gmist** [comment]
```-w``` argument was removed in ac7a04a210ea30c452e9e7187c2295d5240a777f, for now you have to use ```gulp watch``` command.
P.S. You can run ```gulp help```  for more information.

**Comment by bangive** [comment]
thank you
