### ISSUE TITLE
Filters on User Page Inconsistant

### ISSUE THREAD

**Issue by jaxon** [gae-init/gae-init#386]
Using User as an example, I created an admin page for my own Model. Everything works great except filtering (filter_by_link), mostly. I discovered that the same behavior in the User Model.

Sorting (order_by_link) works reliably everywhere, but only certain fields filter properly.

Examples from the live gae-init User page:

Works: 
  https://gae-init.appspot.com/user/?email=test@email.com

Dosn't work:
  https://gae-init.appspot.com/user/?username=lipis
  https://gae-init.appspot.com/user/?name=Lipis

Any help appreciated.

**Comment by gmist** [comment]
It's quite simple - these parameters are not passed as filters in the function [```user_list```](https://github.com/gae-init/gae-init/blob/master/main/control/user.py#L27) or in [```get_dbs```](https://github.com/gae-init/gae-init/blob/master/main/model/user.py#L39) classmethod. Just change it to the following code:
``` python
user_dbs, user_cursor = model.User.get_dbs(email=util.param('email'), username=util.param('username'), name=util.param('name'))
```
or 

``` python
class User(model.Base):
...
  @classmethod
  def get_dbs(
      cls, admin=None, active=None, verified=None, permissions=None, username, name, **kwargs
    ):
    return super(User, cls).get_dbs(
        admin=admin or util.param('admin', bool),
        active=active or util.param('active', bool),
        verified=verified or util.param('verified', bool),
        permissions=permissions or util.param('permissions', list),
        username=username or util.param('username'),
        name=name or util.param('name'),
        **kwargs
      )
```

**Comment by lipis** [comment]
@jaxon Did that solve your issue?
