### ISSUE TITLE
Dependent entities management logic in the base model

### ISSUE THREAD

**Issue by wilfriedE** [gae-init/gae-init#387]
I think it would be cool to have dependency management in the base model.

Lets say there is a ```dependents``` attribute that holds keys to the entity's dependents. 
Similarly there should be an ```owners`` attribute that holds keys to Owner entities. 

With  logic that would make it easy to manage deleting dependent entities and notify owner entities dependent entities have been deleted. 

Lets take for example

Base class 

```
class Base(ndb.Model):
  ...
  dependents = ndb.KeyProperty( repeated=True)
  owners=ndb.KeyProperty( repeated=True)
  ...
  #Modifications during transactions
  ...
  def assign_dependent(self, dependent)
      self.dependents = self.dependents + dependent

  def assign_owner(self, owner)
      self.owners = self.owners + owner

  def remove_dependent(dependent)
       self.dependents  = self.dependents.remove(dependent)

  def remove_from_owner(self)
       for owner in self.owners: 
          owner.remove_dependent(self.key)
  ...
```

Then you can just do things like this:

```
OctoBook = Book(model.Base).put()
Paper =  Paper(model.Base).put()
````

Assign a paper to a book
```
OctoBook.assign_dependent(Paper)
Paper.assign_owner(OctoBook)
````

And when OctoBook gets deleted it makes sure Paper too is deleted.

And if a Paper gets deleted OctoBook gets notified etc...

I think it would be great to have this kind of implementation in Base to enable safe deletions and remove the stress from managing dependencies.

**Comment by lipis** [comment]
There are many different ways of achieving that.. so I don't want to include any in the core project..
