### ISSUE TITLE
CSRF Attack against redirect-uri

### ISSUE THREAD

**Issue by bangive** [gae-init/gae-init#389]
I've just read this article [http://tools.ietf.org/html/rfc6819#section-4.4.1.8] (http://tools.ietf.org/html/rfc6819#section-4.4.1.8). Have you implemented this?

**Comment by lipis** [comment]
For every `form` there is [`{{form.csrf_token}}`](https://github.com/gae-init/gae-init/blob/master/main/templates/profile/profile_update.html#L6) that is provided by [WTForms](http://flask-wtf.readthedocs.org/en/latest/csrf.html)

**Comment by bangive** [comment]
That is for form. For oauth2 login, i think you have not implemented it yet. The link above state that you need to add state parameter when authenticate using oauth2.

**Comment by bangive** [comment]
This link [Encoding claims in the OAuth 2 state parameter using a JWT](https://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state-04) provide a way to secure state parameter using JWT.
