### ISSUE TITLE
Created a new project got this error on Windows 7

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#406]
Ran gulp got this:
![image](https://cloud.githubusercontent.com/assets/2013388/9149161/ea0d99f4-3d50-11e5-9b10-53516ad75343.png)

Ran gulp again and it worked fine.

**Comment by dhstack** [comment]
Was using version 3.2.0 release

**Comment by lipis** [comment]
Is this still an issue?! If it's hard to reproduce or hard to figure out what is going on.. we should just close this..

**Comment by dhstack** [comment]
I haven't encountered it again. Since immediately rerunning gulp fixed it originally, it's not a terribly pressing issue anyway.
