### ISSUE TITLE
Adding new python libraries requires a complete project rebuild before deployement

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#408]
After adding a new python library to `requirements.txt`, it looks like you need to do a complete reset (`gulp reset`) and of the project before you deploy again. Otherwise, you get an `ImportError` when deployed to appengine (ie `No module named foo` error in the logs)

I believe the error is caused because the new python library is not being added to the `main/lib` directory, so it's not being deployed at all. However, **when running the development environment it works fine**. I suspect because the library is being pulled from the `temp/venv/Lib/site-packages`

While it's not a big deal to reset and rebuild the project, I would expect when adding a new python library to `requrements.txt` it would be added automatically to the project when deployed.

**Comment by lipis** [comment]
It works for me.. while the `gulp` task is running in the background and you update the `requirements.txt` the newest libraries are being downloaded into the `main/lib` automatically. When deploying with `gulp deploy` the `lib.zip` is being generated from this folder so it should be all OK. Can someone else verify this issue?

**Comment by dhstack** [comment]
I'm using Windows 7 by the way if that makes a difference.

**Comment by dhstack** [comment]
I also may have added to `requirements.txt` without the `gulp` task running in the background

**Comment by lipis** [comment]
that is also OK.. as it should pickup if eventually you'll run it locally or try to deploy with `gulp deploy`

**Comment by lipis** [comment]
But I'm not sure about how the whole thing reacts on Windows env..
