### ISSUE TITLE
static files not loading

### ISSUE THREAD

**Issue by michals** [gae-init/gae-init#411]
following tutorial:
http://docs.gae-init.appspot.com/tutorial/#run
I got exactly same problem as described here:
http://stackoverflow.com/questions/32458946/gae-init-phonebook-example-css-not-load-correct

I have newest nodejs installed, after npm update'ed and ./run.py -d executed before ./run.py -s.
Any ideas?

**Comment by lipis** [comment]
Yes, I also replied to the SO question. The tutorial is a bit dated.. so you just have to run `gulp` and it should do the trick

**Comment by michals** [comment]
Thanks Lipis for such quick response. It works great.

**Comment by lipis** [comment]
np.. good luck with the rest :)
