### ISSUE TITLE
Sign-in not working properly on Chrome

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#414]
I encounter this reproducible problem on Chrome, but not Firefox or Safari.
1. Go to https://gae-init.appspot.com/
2. Log out (if logged in), and click on "gae-init" in the nav bar.
3. Click on Log in.
4. Select Facebook, authenticate with facebook if necessary

Result: Page still says Sign In. But if you refresh, you can then see that you are logged in.

**Comment by lipis** [comment]
This is known.. not sure if has to do with the eventual consistency or some Chrome's feature with caching :)

**Comment by lipis** [comment]
Actually it doesn't have to do with eventual consistency.. and it's really annoying lately. It didn't happen that often in the past, but now this happens in most cases :/

**Comment by NoahWilcox** [comment]
I'm glad someone brought this up. I thought I had done something odd during customization to make this happen. It actually happens to me 100% of the time when logging in via Google.

**Comment by gmist** [comment]
It's very strange, but on some sites it works without any problems, but other sites give this error.
