### ISSUE TITLE
Gulp is missing from tutorial

### ISSUE THREAD

**Issue by kkinder** [gae-init/gae-init#418]
If you run the commands in the [tutorial](http://docs.gae-init.appspot.com/tutorial/), you'll get a bunch of 404's, because it doesn't mention running npm or gulp.

**Comment by lipis** [comment]
You are right.. the docs are a bit outdated :)

**Comment by lipis** [comment]
Tutorial and docs should be updated for sure: https://github.com/gae-init/gae-init-docs/issues
