### ISSUE TITLE
(Help Wanted) PyCharm Unresolved References

### ISSUE THREAD

**Issue by CrAzE124** [gae-init/gae-init#420]
Hi there, 

I've recently started playing around with Python webdev (coming from a PHP background), and started building a project with gae-init. Working really well, I must say, but it's really irritating to not have autocomplete and what not for some imported modules. 

Let's take for example the `user.py` file in `main.api.v1` - It works fine, but it PyCharm gives me unresolved references to most of the imports - all of them in fact, except `ndb` and `absolute_import`. 

I've attached an image for reference.

Any idea what to do here? As I said, just started playing around with Python!

Thanks for any help!
![pycharm](https://cloud.githubusercontent.com/assets/6757966/10438946/05afc262-7137-11e5-8832-a2d3ecff8018.png)

**Comment by gmist** [comment]
Just mark the `main` directory as `source folder` in the project settings.
<img width="707" alt="screen shot 2015-10-13 at 00 23 21" src="https://cloud.githubusercontent.com/assets/47926/10439203/0b26c8d0-7141-11e5-9f3a-d4b3a41951e5.png">
<img width="250" alt="screen shot 2015-10-13 at 00 22 17" src="https://cloud.githubusercontent.com/assets/47926/10439217/19713358-7141-11e5-958d-96762c27af3b.png">

**Comment by CrAzE124** [comment]
@gmist Thanks, that solved most of the issues, although (in this example), after restart + invalidate, PyCharm still can't pick up the `restful` from `from flask.ext import restful` - any idea? I see that the `__init__.py` in `flask.ext` is supposed to import the whole `flask_restful` library, but I still get "Unresolved Reference" for that.

**Comment by lipis** [comment]
Yes.. the `from flask.ext import restful` might be a bit tricky one.. Not a PyCharm expert :) If everything fails.. we might have to file an issue to JetBrains :)

**Comment by CrAzE124** [comment]
@lipis interesting to note, found [this](https://youtrack.jetbrains.com/issue/PY-7142#tab=Linked%20Issues) on the PyCharm Youtrack page. Weird that it's supported, but it doesn't work out of the box I assume? Will play around a bit and see if I can find any solution (in case this bugs the hell out of anyone else!). 

Thanks for the help (and awesome skeleton app!)

**Comment by lipis** [comment]
It says that is fixed.. strange :) If you find something.. please follow back :) Thanks

**Comment by mroswell** [comment]
This did the trick for me, for a lot of the unresolved references. In particular, the  
File -> Invalidate Caches / Restart... -> Invalidate and Restart
And setting the sources to Main.
https://stackoverflow.com/questions/20479696/pycharm-unresolved-reference-error-on-the-ide-when-opening-a-working-project

**Comment by Pornographictypescript1** [comment]
@lipis https://jquery-knob2.github.io/focusin/
