### ISSUE TITLE
gcloud preview app deploy

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#424]
From the https://dl.google.com/dl/cloudsdk/release/RELEASE_NOTES

> The App Engine Admin API is now the default path for deployments in the
`gcloud preview app deploy` command. This transition should be transparent,
but if you experience any issues and would like to revert to the old
behavior, please run `gcloud config set app/use_appengine_api false`.

**Comment by lipis** [comment]
#395 is unavoidable :/

**Comment by lipis** [comment]
#452

**Comment by dhstack** [comment]
Might be useful to link to the cloud documentation somewhere if it isn't already in the gae-init docs.
https://cloud.google.com/sdk/gcloud/reference/preview/app/deploy

**Comment by lipis** [comment]
make a new issue in docs..

**Comment by dhstack** [comment]
Done #532 . Can't add the "docs" label though
