### ISSUE TITLE
CSS is served with application/octet-stream mime type

### ISSUE THREAD

**Issue by nazroll** [gae-init/gae-init#426]
The recent update to Google App Engine has a significant, but small change.

I observed that static files is now uploaded to a staging environment as a Google Cloud Storage bucket when deployed to Google Cloud. 

With this small change, CSS is unexpectedly served as ```application/octet-stream``` mime type.

I tried a fix by duplicating a set of rules from ```app.yaml```, making it specific and properly assigned to the right mime type. In this example: ```text/css```
```
- url: /p/(.*\.css)
  static_files: static/\1
  upload: static/(.*\.css)
  mime_type: text/css
  expiration: 1000d
```

Deploy.
It worked. CSS is not serving with the correct mime type.

**Comment by lipis** [comment]
Not sure if it was just that version.. but in a few latest deployments the mime type is correct for CSS.. so I'm closing this one.
