### ISSUE TITLE
Error: no writecb in Transform class

### ISSUE THREAD

**Issue by emilorol** [gae-init/gae-init#435]
Hi,

When running gulp I am getting this error:

```ssh
[Error: no writecb in Transform class]
```

See output:

```ssh
[emil@localhost myapp]$ gulp
[15:52:56] Using gulpfile ~/Work/myapp/gulpfile.js
[15:52:56] Starting 'default'...
[15:52:56] Starting 'run'...
[15:52:56] Starting 'install_dependencies'...
[15:52:56] Starting 'npm'...
[15:52:56] Finished 'run' after 37 ms
[15:52:56] Starting 'watch'...
[15:52:56] Finished 'watch' after 19 ms
[15:52:56] Starting 'reload'...
[15:52:59] Finished 'reload' after 2.71 s
[15:52:59] Finished 'default' after 2.77 s
[15:52:59]  $ npm install
[15:53:01] Finished 'npm' after 5.12 s
[15:53:01] Starting 'pip'...
[15:53:01]  $ python run.py -d
[15:53:01] Finished 'pip' after 356 ms
[15:53:01] Starting 'bower'...
[15:53:01]  $ node_modules/.bin/bower install
[15:53:02] Finished 'bower' after 901 ms
[15:53:02] Starting 'copy_bower_files'...
[15:53:03] Finished 'copy_bower_files' after 223 ms
[15:53:03] Finished 'install_dependencies' after 6.6 s
[15:53:03] Starting 'ext:dev'...
[15:53:03] Starting 'script:dev'...
[15:53:03] Starting 'style:dev'...
[Error: no writecb in Transform class]
[15:53:05] Finished 'script:dev' after 2.04 s
[15:53:05] /home/emil/Work/myapp/main/static/dev/script/script.js reloaded.
[15:53:05] Finished 'ext:dev' after 2.2 s
[15:53:05] /home/emil/Work/myapp/main/static/dev/script/ext.js reloaded.
```

What am I missing?

**Comment by lipis** [comment]
How old is your node version?! Try getting the latest one and see what happens.

**Comment by emilorol** [comment]
[emil@localhost .bin]$ node --version
v0.10.36
[emil@localhost .bin]$ npm --version
1.3.6

**Comment by lipis** [comment]
Yep! Time to upgrade
```shell
$ node --version
v5.1.0

$ npm --version
3.3.12
```

**Comment by emilorol** [comment]
wow, I created a Linux VM (latest Fedora) to play with GAE and your framework and I didn't stop to check the version of node or npm as I was thinking they were the latest.

*Note:* I had spend more time setting up the tools for development that developing. I haven't touch a single python file yet, LOL.

*Note 2:* Maybe a way to help new comers like me will be to (newbies branch) have a single CSS file and a single JS file for the custom modification and all other major libraries running from a CDNs.

Thank you for putting this together.

**Comment by lipis** [comment]
Yes the initial setup might be trivial sometimes.. but TBH all these tools are needed or already there if you are already programming in Python and and the latest web technologies. But once you're done, then you're golden :)

As for your second note, this framework is not exactly targeting newbies and since the whole thing is setup to be production ready that wouldn't be a good idea I think.. :)

Good luck.

P.S. why creating a VM instead of having that on your normal OS?

**Comment by emilorol** [comment]
The reason for the VM is a bit of OCD when testing new things I hate to have lingering files or libraries floating around, plus if I screw up at some point I can just wipe it out and rebuilt it and keep my OS clean.

**Note:** as you have probably hear/read a bunch of times the project could use few intro videos and a review on the documentation. A lot of people are attracted to GAE and python coming from other programming languages and/or environments, but the learning curve is hard.

**Comment by lipis** [comment]
Fair enough..

You are right and I was thinking of creating some intro videos or updating the documentation, but unfortunately I don't have much time :| One day.. :) The project it self is alive in kicking though :sunglasses:

**Comment by emilorol** [comment]
Just to confirm, the old version of node was the problem. After upgrading it to the latest version it all works. Thank you.

**Comment by lipis** [comment]
Awesome!

**Comment by lipis** [comment]
Hey @emilorol while I appreciate the effort of writing a wiki.. I think I'll disable it and will start updating the  github.com/gae-init/gae-init-docs to include these kind of guides there..

Also of course updating Node.js to the latest is always a good idea and I might include it in the docs.gae-init.appspot.com/requirement/ list (and add there Gulp.js) but for developing with gae-init you don't need to install Grunt, Bower or CoffeeScript globally and there is no need to edit the `run.py` file.. 

So overall it's a bit confusing as it is right now..

**Comment by emilorol** [comment]
I noticed the switch from Grunt to Gulp, but I installed it just in case. Also about Bower and CoffeeScript globally I did it for future projects. I had to specify the path for GAE in run.py because I keep getting the "No Google App Engine found error" ( Fedora 23 ) from Gulp even with the latest Node.JS. 

In other words, the wiki was like a list of things to do for a guy like me coming from another programming language and have never setup the required tools.

**Comment by lipis** [comment]
For a guy like you.. but if these things written on a gae-init wiki, people might think that they also need that, when the actually don't :)

So I added Gulp to the requirements.. http://docs.gae-init.appspot.com/requirement/ and that's all you need really.. (where is also written than you need the latest version of Node :D)

As for the editing `run.py` instead you might want to add app engine to your `PATH`. Also confusing for the newcomers..

**Comment by lipis** [comment]
That line is also not needed `npm install --save-dev gulp`.. so overall I'll turn off wiki and if you feel like contributing to the docs.. just click the edit button or directly in GitHub :)

**Comment by emilorol** [comment]
I did add the Google App Engine path to the PATH in ~/.bash_profile and I source it and I even reboot the VM and if I print the PATH ($ echo $PATH) it will show me that is there, but I keep getting the error.

I agree with you, let's remove the Wiki to avoid confusion.

**Comment by emilorol** [comment]
For the upcoming documentation I have few questions, so I will open a new issue. Close this one.

**Comment by lipis** [comment]
New issues are always welcome..
