### ISSUE TITLE
Magic repo(s)

### ISSUE THREAD

**Issue by emilorol** [gae-init/gae-init#436]
Hi,

Is there a way to see the code generated by "Magic" like in a repo or branch without doing ./magic.py?

**Comment by lipis** [comment]
yes sure.. create a new project and check it out on http://magic.gae-init.appspot.com

**Comment by emilorol** [comment]
I mean to see the code of the models or controllers online like you can do with the phonebook tutorial by going to: 

https://github.com/gae-init/phonebook

Maybe something like:

https://github.com/gae-init/magic

and then all branches inside it.

**Comment by lipis** [comment]
That code is not open sourced if you mean the project it self. 

Login and create one test: http://magic.gae-init.appspot.com/project/ or check out the [Phonebook](http://magic.gae-init.appspot.com/project/5820623766945792/) (you have to run the ./magic.py to see the generated though).

**Comment by emilorol** [comment]
The generated code is what I am after not the code use to generate it and I was trying to avoid going thru the clone process and then calling the ./magic with the ID

**Comment by lipis** [comment]
Yeah.. for the example just run these [5 lines](http://magic.gae-init.appspot.com/project/5820623766945792/)..

```shell
git clone https://github.com/gae-init/gae-init.git phonebook
cd phonebook
./magic.py -p 5820623766945792 
npm install
gulp
```

**Comment by emilorol** [comment]
Yes, that part I got. I am just learning python by following the code and in one screen I have the editor and in the other one a web browser. I am going to do that then I will create a repo under my account with the code. 

Once again thank you.

**Comment by lipis** [comment]
yep... that one way :)

**Comment by emilorol** [comment]
You can close this too.

**Comment by lipis** [comment]
Feel free to close things on your own as well.. :)
