### ISSUE TITLE
Documentation ideas and/or questions

### ISSUE THREAD

**Issue by emilorol** [gae-init/gae-init#439]
## Ideas:

**A How To section**
- How to create a custom and clean URL?
- Using the GAE Search API with/out Facets?
- REST API 
- Connecting HTML fields to data (radios, select, textfield and text area)
- Referencing data in forms (artist -> song -> album)
- Disable all user registrations or force a single Open ID

**API Documentation**
- Generate documentation from code documentation 

**Generators**
- Generate basic controllers, models and/or template with CRUD operations and lists

**Note:** There is a big change some of the ideas exist already either by the existing app or by using a library, I am just listing my findings and questions while learning Python and using GAE Init.

**Comment by lipis** [comment]
> A How To section

A how to section is a good idea, and I was thinking about it for quite some time. Maybe it's time to start it and have at least some placeholders for people to fill up.

> API Documentation

This one needs some love.. http://docs.gae-init.appspot.com/reference/ I didn't (still don't) want to fill the code with docs.. so maybe someday in the future..

> Generators

That was the whole idea with the http://magic.gae-init.appspot.com :)

---------

Just don't get confused that this will the base for learning App Engine.. :) While it's easy to start with gae-init, it requires you to learn App Engine in general if you want to move deeper..

P.S. It's **gae-init**, not GAE init, or GAE Init or any other combination :)

**Comment by emilorol** [comment]
Perfect. 

Where can I start with the documentation?

**Comment by emilorol** [comment]
For the API documentation, what about using something like:

https://docs.python.org/2/library/pydoc.html

**Comment by lipis** [comment]
That's the main project for documentation.. http://docs.gae-init.appspot.com but unless you want to edit anything there on the spot.. I'll suggest to wait a bit until I'll add the *How To* section and then it will be easier to add stuff :)

**Comment by lipis** [comment]
@emilorol  http://docs.gae-init.appspot.com/howto/ something like this?

**Comment by emilorol** [comment]
It's looking good.

**Suggestions:**

1. I will add the initial tools setup, like what I try to do in the Wiki I wrote.

2. Let's add to the how to how to create your own model, controller and template

3. Connecting text fields, text areas, selects, radios to the data

4. Relationship in data and forms between kinds

5. Autocomplete for tags. Lookup existing or add new one

**Note:** When I started to dive into Google App Engine using python I found the [Ferris 2 framework](https://github.com/jonparrott/ferris2/), but I discard it as it has not been updated in a long time. However it did had [scaffolding](http://ferris-framework.appspot.com/docs/tutorial/4_scaffolding.html) and a logic like that might benefit **gae-init** . This comment is following the mention to a generation of code.

**Comment by lipis** [comment]
> 1. I will add the initial tools setup, like what I try to do in the Wiki I wrote.

Isn't that enough? http://docs.gae-init.appspot.com/requirement/

**Comment by lipis** [comment]
> 2. Let's add to the how to how to create your own model, controller and template

That was the idea of the tutorial :) http://docs.gae-init.appspot.com/tutorial/#model

**Comment by emilorol** [comment]
http://docs.gae-init.appspot.com/requirement/ is enough if you are familiar with those tools or you already have them. I had an issue with the Google Cloud SDK that I also need it to download the Google App Engine SDK, so I end up only using the Google App Engine SDK.

The way you wrote the application was easy to follow the phonebook tutorial to extend or customize the app, but I spend almost 3 days figuring out the development tools.

**Comment by emilorol** [comment]
The tutorial was a big help getting started here, but like I mention in #436 access to the code ( without any magic ) on those apps will give you even more inside. Using the code of the apps as tutorials will ease the learning curve even more.

**Comment by lipis** [comment]
> http://docs.gae-init.appspot.com/requirement/ is enough if you are familiar with those tools or you already have them. I had an issue with the Google Cloud SDK that I also need it to download the Google App Engine SDK, so I end up only using the Google App Engine SDK.

We just have to update this part in order to include the GAE SDK as it seems that it's not coming preinstalled.. http://docs.gae-init.appspot.com/requirement/#gae 

My point is that I don't want to repeat the same thing in two different sections.. the requirements page should be self contained and if you manage to run all the commands that you see there in red.. that means that your env is ready!
