### ISSUE TITLE
Using pygithub3

### ISSUE THREAD

**Issue by sparkline-charlie** [gae-init/gae-init#451]
Hi Lipis,

As reference from my email last time.

Please check issue I've encountered while using pygithub3

I've tried installing package the PYGITHUB3 in the gae-init you've created.

For the overview, i want to create a gantt chart for issues in the GITHUB by retrieving all data and displaying it as gantt chart.

But after coding the retrieval of repository of a particular user, i've encountered this error.

![image](https://cloud.githubusercontent.com/assets/15224937/11867412/e011a49c-a4eb-11e5-8a88-13f8bfcfe2f3.png)

![image 1](https://cloud.githubusercontent.com/assets/15224937/11867430/ecd76a54-a4eb-11e5-9313-0d8e2bf6dff4.png)

Hope you could assist me.

**Comment by lipis** [comment]
Try the following:

Add the following to your requirements.txt

```
pygithub==1.26.0
```

The run `gulp` from the root folder of the project and finally add this to your `main.py`

```python

import github

...

@app.route('/gh/')
def gh():
  g = github.Github('username', 'password')
  names = []
  for repo in g.get_user().get_repos():
    names.append(repo.name)
  return ' '.join(names)
```

And check the result on [http://localhost:8080](http://localhost:8080/gh/).

**Comment by gmist** [comment]
Looks like that pygithub3 required ```requests>=2.0.0``` but ```requests``` higher than version 2.3.0 do not work properly on GAE. So try the following steps:
1. Add to ```requirements.txt```
```
requests==2.3.0
```
2. Add to ```main/appengine_config.py``` after line 15 the following code:
``` python
from google.appengine.tools.devappserver2.python import sandbox
sandbox._WHITE_LIST_C_MODULES += ['_ssl', '_socket']
```

**Comment by lipis** [comment]
(Wrong pygithub.. :dash: ignore mine..)

**Comment by sparkline-charlie** [comment]
Hi everyone. Thanks for the quick response. I'll try this.
I'll keep you posted. Thank you!

**Comment by sparkline-charlie** [comment]
Hi,

It works! I can retrieve the data using the above instruction

Output:
![image](https://cloud.githubusercontent.com/assets/15224937/11887435/26eb66ae-a56f-11e5-8e09-91c82e8b05b7.png)

Code used:
![image](https://cloud.githubusercontent.com/assets/15224937/11887487/acfc5c44-a56f-11e5-902b-5fcdcf9ff36f.png)


from pygithub3 import Github
from main import app

username='test'
password='test'
auth = dict(login=username, password=password)
gh = Github(**auth)

@app.route('/gantt/')
def index():
    names = []
    for repo in gh.repos.list().all():
        names.append(repo.name)
    return ' '.join(names)

Thank you for this support.

**Comment by lipis** [comment]
:dancer:

**Comment by lipis** [comment]
@sparkline-charlie  You made me try what I wanted to do for a long time http://githubstats.lip.is :) and here is the source https://github.com/lipis/github-stats

**Comment by sparkline-charlie** [comment]
wow this is great. :-)
