### ISSUE TITLE
Arch Linux breaks when running Python 3

### ISSUE THREAD

**Issue by flamusdiu** [gae-init/gae-init#460]
I modified run.py to fix this issue

```
diff --git a/run.py b/run.py
index ee837d1..c81a55e 100755
--- a/run.py
+++ b/run.py
@@ -53,6 +53,7 @@ ARGS = PARSER.parse_args()
 BAD_ENDINGS = ['pyc', 'pyo', '~']
 GAE_PATH = ''
 IS_WINDOWS = platform.system() == 'Windows'
+IS_VIRTUAL_ENV = 'VIRTUAL_ENV' in os.environ
 
 
 ###############################################################################
@@ -60,7 +61,9 @@ IS_WINDOWS = platform.system() == 'Windows'
 ###############################################################################
 DIR_MAIN = 'main'
 DIR_TEMP = 'temp'
-DIR_VENV = os.path.join(DIR_TEMP, 'venv')
+DIR_VENV = os.environ['VIRTUAL_ENV'] \
+    if IS_VIRTUAL_ENV \
+    else os.path.join(DIR_TEMP, 'venv') 
```

This checks if you are in a virtual env and uses that instead of creating a new instance. I have to run everything inside of python2.7 which means I have create the virtual env before setting up the application. This might be only an issue where python3 is the primary python on a system.

**Comment by lipis** [comment]
Is this still an issue or we can just close it?

**Comment by flamusdiu** [comment]
it's still an issue. if you are running on a system with Python3 as the default interpreter.

**Comment by flamusdiu** [comment]
I recloned the repo and did a clean setup with the newest branch. I still get this:

```
[13:14:28] Using gulpfile ~/Documents/git_projects/gae-init/gulpfile.js
[13:14:28] Starting 'init'...
[13:14:28] Starting 'pip'...
[13:14:28]  $ python run.py -d
  File "run.py", line 95
    print '[%s] %12s %s' % (timestamp, script, filename)
```

This is the different between Python2 and Python3. Outside of a virtual env this fails if Python3 is the primary python version. Since the application suppose to create a virtual env to run in during the setup,  I would guess the run script would work in both Python2 and Python3 (or check if in a virtual env and use that instead of creating a new one).

**Comment by lipis** [comment]
Not sure what we can do if your default Python is 3.. I mean to develop for App Engine you need to do it in 2.7 so I would say it's a requirement.. We are calling the `python run.py -d` from another script and I'm not willing to add an extra check if you have Python 3 instead 2.. 

So I think I'll close this for now..
