### ISSUE TITLE
ImportError and AttributeError during Unit testing

### ISSUE THREAD

**Issue by Sparkline-Dexter** [gae-init/gae-init#461]
Hi guys, I encountered the `ImportError` and `AttributeError` in unit testing.
First I have this ImportError: No module named 'main'.
  I fixed this by adding `sys.path.append('main/')` on my `test_sample.py`

Now I have this AttributeError,
```
File "main/model\base.py", line 15, in Base
   version = ndb.IntegerProperty(default=config.CURRENT_VERSION_TIMESTAMP)
AttributeError: 'module' object has no attribute 'CURRENT_VERSION_TIMESTAMP'
```

Is there already a thread or solution to my problem. I'm still a newbie in Python and Google App Engine. I will greatly appreciate your help on this matter.

**Comment by lipis** [comment]
It looks like it's because the Google App Engine is not in the path when you are importing the `config.py` with your Unit Tests..

https://github.com/gae-init/gae-init/blob/master/main/config.py#L12

**Comment by Sparkline-Dexter** [comment]
Thank you for the reply. I appreciate your kindness. For now I'll just check the PATH PYTHON_PATH to see whether there is a mismatch between library and python.  I'm using Python 2.7.10 in my project by the way.
