### ISSUE TITLE
Question - easy way to turn off google login?

### ISSUE THREAD

**Issue by savraj** [gae-init/gae-init#464]
Is it true that the app must accept google login, because you need that to access the app admin pages? Is that correct?  Is there an easy way to turn off google login so it's just email/password login?  I haven't entered a Google client ID and secret, yet the app still allows google by Default. I have turned on email/password login.

Also, let me know if this is the right place to submit a question. If not, please forgive me. Thanks!

**Comment by lipis** [comment]
First of all that's the perfect place to ask these kind of questions.. :)

You can always make someone else an Admin so anyone can access the admin pages.. even if you're going to update the User model from the Datastore admin of Google App Engine..

Also it might be confusing that there are basically 2 _Google_ logins.. but one is the built in App Engine login and the other one is the Google Plus OAuth login.. (if you'll enter the Client ID)..

Now the first one you can't really disable from the settings (maybe we should add it though) but you can always [do something like this](https://github.com/gae-init/gae-init/compare/disable-gae) to _turn it off_ :)

**Comment by savraj** [comment]
Thanks for posting this. Luckily, I had already made the exact same change (in a slightly different way), which means I had the right instincts ;) I may turn it back on later, but I want to keep it simple at the beginning. Thanks!!!

**Comment by lipis** [comment]
You're very welcome :)
