### ISSUE TITLE
[magic] DateTime Property Error "Not a valid datetime value" 

### ISSUE THREAD

**Issue by jaxon** [gae-init/gae-init#466]
![screen shot 2016-01-23 at 4 52 48 pm](https://cloud.githubusercontent.com/assets/31676/12533799/cd75b5a8-c1f1-11e5-9c14-a792a6068bfd.png)

Not a valid datetime value

**Comment by gmist** [comment]
You should explicitly specify the date format
``` python
class MyForm(wtf.Form):
  mydate = DateField('My date', format='%m/%d/%Y')
```

**Comment by lipis** [comment]
After updating to this https://github.com/gae-init/gae-init/commit/d980473583bb3cdca17d6757f38e6c93d09bc4e2  magic has now a new option for the HTML field.. `datetime_field` choose that one and it will work..

**Comment by lipis** [comment]
@gmist Didn't know about the `format=`.. thanks!

**Comment by jaxon** [comment]
@lipis Running with `datetime_field` results in this error:
 
UndefinedError: 'jinja2.environment.TemplateModule object' has no attribute 'datetime_field'

**Comment by lipis** [comment]
yes.. sync with the latest master on gae-init or just get this one: https://github.com/gae-init/gae-init/commit/d980473583bb3cdca17d6757f38e6c93d09bc4e2
