### ISSUE TITLE
Using requests version 2.6.0

### ISSUE THREAD

**Issue by nazroll** [gae-init/gae-init#467]
I have to use `requests` 2.6.0 instead of the latest (2.9.1) because I need to support the braintree python library.

Will it break the latest gae-init release?

**Comment by lipis** [comment]
well requests  is not used in gae-init  by default.. so not sure how it can break things

**Comment by nazroll** [comment]
@lipis i need to ask, just to be sure. thanks man

**Comment by lipis** [comment]
:dancer:

**Comment by gmist** [comment]
@nazroll ```requests``` 2.6.0 may be working unstable, so I recommend using ```requests``` 2.3.0 with the addition of modules ```['_ssl', '_socket']``` to sandbox._WHITE_LIST_C_MODULES:
```
main/appengine_config.py:
```

``` python
if os.environ.get('SERVER_SOFTWARE', '').startswith('Google App Engine'):
  sys.path.insert(0, 'lib.zip')
else:
  ...
  from google.appengine.tools.devappserver2.python import sandbox
  sandbox._WHITE_LIST_C_MODULES += ['_ssl', '_socket']
```

**Comment by lipis** [comment]
:bow:

**Comment by nazroll** [comment]
@gmist great! thank you. i'm going to try this out
