### ISSUE TITLE
Can't reach docs site in Arch Linux/Chrome v48 (Beta)

### ISSUE THREAD

**Issue by flamusdiu** [gae-init/gae-init#468]
![screen24](https://cloud.githubusercontent.com/assets/1879197/12697479/9876ee74-c752-11e5-9f8c-89a64520e287.png)

This is what Chrome gives me when I visit https://docs.gae-init.appspot.com/ and refuses to actually go past the issue.

**Comment by lipis** [comment]
http://docs.gae-init.appspot.com/ or if you want HTTPS then use this URL:

https://docs-dot-gae-init.appspot.com/

**Comment by flamusdiu** [comment]
well, http://docs.gae-init.appspot.com redirects to the https site automatically and fails. The second link works. Any link that goes to docs.gae-init.appspot.com seems always be the broken https url.

**Comment by flamusdiu** [comment]
Oh, this includes the "Documentation" link on the main page.

**Comment by lipis** [comment]
It doesn't redirect me.. and it shouldn't..

**Comment by lipis** [comment]
works by design here.. can someone else verify?

**Comment by flamusdiu** [comment]
@lipis which browser are you using?

**Comment by flamusdiu** [comment]
![capture](https://cloud.githubusercontent.com/assets/1879197/12699427/89fc6776-c788-11e5-8050-f84167aa5a4a.PNG)

Here's the same page in Microsoft Edge (Windows 10). it allows a by-pass. Chrome Beta (v48) in Windows 10 does not.

**Comment by lipis** [comment]
what about http://babel.gae-init.appspot.com?

**Comment by flamusdiu** [comment]
I'll check this evening. I'll let you know. Thanks!
