### ISSUE TITLE
How to create a form input like a check_box field in a list view table

### ISSUE THREAD

**Issue by voscausa** [gae-init/gae-init#474]
For instance to check a table row input in the contact_list.html of the tutorial:
  
![row selection](https://cloud.githubusercontent.com/assets/1223469/12790847/9bedbeb6-caa4-11e5-8df3-5f0f33c42dac.png)

**Comment by lipis** [comment]
You can see how it is done in the `/admin/user/`

Here is the script:
https://github.com/gae-init/gae-init/blob/master/main/static/src/script/site/user.coffee#L7-L38

and here is the html:
https://github.com/gae-init/gae-init/blob/master/main/templates/user/user_list.html#L103

**Comment by voscausa** [comment]
OK, clear. 
I hoped you had another forms api (magic jinja form macro) to create a form input  in a table row.

I used:

```
          <td class="text-center">
            <label class="not-link">
              <input type="checkbox" name="delete" value="{{contact_db.key.id()}}">
            </label>
          </td>
```

**Comment by lipis** [comment]
you can put the `not-link` to the whole cell..

**Comment by lipis** [comment]
But speaking of [_magic_](http://magic.gae-init.com).. delete is coming soon :D :walking:

**Comment by voscausa** [comment]
Thnx again.
