### ISSUE TITLE
LetsEncrypt Cloud Shell erorr

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#477]
Tried following the [instructions](http://docs.gae-init.appspot.com/howto/#letsencrypt) for setting up LetsEncrypt (nice add by the way), but got stuck on the first step. Any idea what is going on here?

Got a "cannot start container" error:
![image](https://cloud.githubusercontent.com/assets/2013388/12830483/67787284-cb44-11e5-8c33-b29686bcb42d.png)

**Comment by lipis** [comment]
haven't done it for a while now.. but it worked for me for couple of tests.. :)

**Comment by dhstack** [comment]
```
git clone https://github.com/letsencrypt/letsencrypt
cd letsencrypt
```
and
```
sudo ./letsencrypt-auto -a manual certonly
```
commands from [here](http://blog.seafuj.com/lets-encrypt-on-google-app-engine) got me to the installation screen, but upon learning that certificates are [only good for 90 days](https://community.letsencrypt.org/t/pros-and-cons-of-90-day-certificate-lifetimes/4621/2) and would have to be renewed manually, I am less inclined to use it. Is there a way to automatically renew the certificates?

**Comment by lipis** [comment]
Support a few issues :)
https://code.google.com/p/googleappengine/issues/detail?id=12535
https://code.google.com/p/googleappengine/issues/detail?id=12615

**Comment by dhstack** [comment]
Done. Looking forward to the rapid implementation of this by the GAE team.

I'm just going to use http for now on my custom domain, so closing this issue.
