### ISSUE TITLE
/profile/password/ - old password is optional, but is actually required?

### ISSUE THREAD

**Issue by savraj** [gae-init/gae-init#479]
Noticed that it is set as optional in the controller -- why is that? if you try going forward without the old password it errors -- this is the page

![image](https://cloud.githubusercontent.com/assets/387613/12925069/8e2320f2-cf2a-11e5-941e-8160f012d38f.png)

**Comment by lipis** [comment]
yez..

**Comment by savraj** [comment]
thanks!

**Comment by lipis** [comment]
thanks for reporting..
