### ISSUE TITLE
Silly question on difference between current_user in template and auth.current_user_db()

### ISSUE THREAD

**Issue by savraj** [gae-init/gae-init#484]
In the Welcome template (welcome.html) we see a reference to a ```current_user``` object, and in other places we see a reference to ```auth.current_user_db()``` for example in profile.html. What's the difference between these two objects? I noticed that current_user doesn't have the same set of properties as current_user_db(). 

Forgive my ignorance, please! For some reason I thought these two objects would be identical.

Thanks,
Savraj

**Comment by mdxs** [comment]
Where on the `welcome.html` do you see a `current_user` object?

**Comment by savraj** [comment]
Sorry, say: /main/templates/bit/user_menu.html

**Comment by lipis** [comment]
In the templates if you want to have the access to the `user_db` you would use it via `current_user.user_db` and in order to make sure that it exists:

```
# if current_user.id > 0
  {{current_user.user_db.name}} - {{current_user.user_db.email}}
# endif
```

https://github.com/gae-init/gae-init/blob/master/main/auth/auth.py#L51-L54

**Comment by lipis** [comment]
unless of course the `login_required` or `admin_required` is used so you don't have to check `if current_user.id > 0`.

**Comment by savraj** [comment]
Ah ok brilliant, thanks for the highlighted lines.

**Comment by lipis** [comment]
P.S. There are no silly questions :) Bunch of things are happening and they should be [documented](http://docs.gae-init.com/howto/) eventually..
