### ISSUE TITLE
'module' object has no attribute 'check_output'

### ISSUE THREAD

**Issue by sparkline-charlie** [gae-init/gae-init#485]
Hello,

Hope you could help me in my issue.

Currently, i'm running this line of code:
**output = subprocess.check_output(cmd, shell=True)**

But encountered this error:
**'module' object has no attribute 'check_output'**

Is there any settings i need to do since the **subprocess** module is included in my libraries

Thanks in advance!

**Comment by mdxs** [comment]
Perhaps you named one of your files "subprocess.py" file, thus the "check_output()" is tried for that file/module, whereas you probably are trying to call the https://docs.python.org/2/library/subprocess.html library... which I think you cannot do on Google Appengine in production; see http://stackoverflow.com/questions/10803603/invoke-terminal-script-on-google-app-engine for a discussion about this.

**Comment by sparkline-charlie** [comment]
Hi mdxs,

Thanks for the reply. After researching, it seems google app engine is prohibited to use subprocess.check_output since it is accessing the physical hardware. Security purpose i guess. Is there any alternative to this if i want to run shell command?

**Comment by lipis** [comment]
You will have to find something alternative to App Engine.. because on App Engine.. you simply can't do that..
