### ISSUE TITLE
Using Task Queue API with authentication

### ISSUE THREAD

**Issue by nazroll** [gae-init/gae-init#486]
I'm looking for ideas on a good approach to use Task Queue API with authentication.

Any thoughts?

**Comment by mdxs** [comment]
Please explain what you want to do.

**Comment by lipis** [comment]
@nazroll Please respond if you need more help.. for now I'll close this.

**Comment by topless** [comment]
I will take a wild guess here. I suspect you want to trigger the queue api with an authenticated request. Decorate the endpoint handler `/api/v1/myqueue` with the `@auth.login_required` decorator, like this ,you  will be able to trigger the queue only if you authenticated!
