### ISSUE TITLE
Won't run on windows 10

### ISSUE THREAD

**Issue by b-cannon** [gae-init/gae-init#491]
After installing the requirements with no problems, after typing 'gulp' I  get an error with dev_appserver.py.  First a windows error came up saying there was nothing to run it with.  After I pointed it to python 2.7, I got an error 'too few arguments'.

**Comment by dhstack** [comment]
It works just fine for me on Windows 10. In the past it has taken me a couple times of running `gulp` before everything was installed after a project reset. Have you tried running it again?

**Comment by b-cannon** [comment]
Yes, I've tried several times.  I looked to make sure everything was on the right path as well.  I'm still getting the same message with dev_appserver.py: error: too few arguments.  I have no idea what other arguments I would need because I can start gae dev server just fine for other projects.

**Comment by b-cannon** [comment]
ok, I tried running it directly through the gae launcher and it ran fine.  So I guess that would mean it has something to do with gulp.  I have never used gulp so I don't really know what the fix would be.  Since I can install it with no problems, is there any drawback by running it through the launcher rather than gulp?

**Comment by dhstack** [comment]
The only things I can think of that you won't get when not using the gulp
command would be the automatic reloading of the browser and recompiling the
less and coffeescript.


*--*
*David Stack*
Business Strategist
davidhstack.com
<http://davidhstack.com?utm_medium=email&utm_source=signature>

**Comment by dhstack** [comment]
Which directory are you running `gulp` from? It should be your project root directory (not the "main") folder.

**Comment by b-cannon** [comment]
Yes, I'm just in the root folder.  So following the tutorial it was ...\phonebook>

**Comment by lipis** [comment]
Is that still an issue?

**Comment by joenorton** [comment]
Just tested this on Win 10; no problems. Just git clone, cd into the project directory, npm install and gulp.

**Comment by lipis** [comment]
then I'll just close it for now..
