### ISSUE TITLE
Running 'gulp' command just open the dev_appserver.py file

### ISSUE THREAD

**Issue by alex-deneuvillers** [gae-init/gae-init#492]
After running 'gulp' on my terminal (Windows 7) I get the following : 

> [11:42:32] Using gulpfile ~\PycharmProjects\Project\gulpfile.js
> [11:42:32] Starting 'default'...
> [11:42:32] Starting 'run'...
> [11:42:32] Starting 'init'...
> [11:42:32] Starting 'pip'...
> [11:42:32] Finished 'run' after 203 ms
> [11:42:32] Starting 'watch'...
> [11:42:32] Finished 'watch' after 131 ms
> [11:42:32] Starting 'reload'...
> [11:43:20] Finished 'reload' after 47 s
> [11:43:20] Finished 'default' after 48 s
> [11:43:20]  $ python run.py -d
> [11:43:34] Finished 'pip' after 1.02 min
> [11:43:34] Starting 'bower'...
> [11:43:34]  $ node_modules.bin\bower install
> [11:43:47] Finished 'bower' after 14 s
> [11:43:47] Starting 'copy_bower_files'...
> [11:43:51] Finished 'copy_bower_files' after 3.42 s
> [11:43:51] Finished 'init' after 1.3 min
> [11:43:51] Starting 'ext:dev'...
> [11:43:51] Starting 'script:dev'...
> [11:43:52] Starting 'style:dev'...
> [11:44:06] Finished 'style:dev' after 14 s
> [11:44:06] Finished 'script:dev' after 15 s
> [11:44:06] Finished 'ext:dev' after 15 s
> [11:44:06] C:\Some\Path\Project\main\static\dev\script\ext.js reloaded.
> [11:44:06] C:\Some\Path\Project\main\static\dev\script\script.js reloaded.
> [11:44:06] C:\Some\Path\Project\main\static\dev\style\style.css reloaded.
> [11:44:07]  $ python run.py -s

And instead of launching the dev server, it just opens the dev_appserver.py file in my editor.

**Comment by lipis** [comment]
is this still an issue?

**Comment by alex-deneuvillers** [comment]
Yeah, I still have this issue. The watch commands works fine but the devappserver.py just opens so I have to use the Google App Engine Launcher.

**Comment by lipis** [comment]
Could you please install the latest version of the `gcloud` from: https://cloud.google.com/sdk/ and also get a fresh copy of `gae-init` and try it again?

**Comment by alex-deneuvillers** [comment]
Okay now, after gulp launch _python run.py -s_ , it launch an empty python shell and prompt _C:\...\gae-init-4.1.0\main\static\dev\script\script.js reloaded._ and get stuck on it.

**Comment by lipis** [comment]
can you post here all the output that you are getting from the following commands?

```
gulp reset
```

```
npm install
```

```
gulp
```

You can paste the results into a gist.. or directly here as code :)

**Comment by alex-deneuvillers** [comment]
Okay, here is the gist with the several outputs, I've made two : one with the errors showed on my cmd, and another one with the result of the command added to a txt file.

[https://gist.github.com/alex-deneuvillers/70104c85bd281deb8293a998b4e9aad1](url)

**Comment by mdxs** [comment]
@alex-deneuvillers Perhaps start fresh and try the improved documentation at http://docs.gae-init.appspot.com/requirement/

**Comment by snackattas** [comment]
I'm having this same issue.  And I used the improved docs?  Any idea what could be causing it?  Is it possible that having both gcloud and google app engine installed has something to do with it?

**Comment by topless** [comment]
When you install `gcloud` if it finds app engine locally it tells you where it is and suggests to remove it. I would suggest the same. Keep only `gcloud` tool. If you open a terminal and fire `dev_appserver.py` what happens? I will have access to a windows machine today so I will also have a look.

**Comment by adsodemelk** [comment]
Try associating your .py files with python instead of the editor.

**Comment by mdxs** [comment]
Is this still an issue? (and if so, on which platform... guess it was Windows)
