### ISSUE TITLE
Prevent gulp-cssnano from changing z-index by default

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#493]
I spent way to many hours trying to figure out why the local hosted version of my site worked fine and the deployed version was not when it came to displaying certain elements. It turns out gulp-cssnano changes z-index values ***by default***. I suggest we change this behavior, as [this issue](https://github.com/ben-eb/gulp-cssnano/issues/8) suggests, and pass `{zindex: false}` to cssnano until version 4 is released that changes this default behavior.

**Comment by mdxs** [comment]
Could you propose what to change where in a Pull Request?

**Comment by dhstack** [comment]
Yes, working on that now

**Comment by mdxs** [comment]
Thnx, looking forward; though I didn't experience the issue myself.

**Comment by dhstack** [comment]
It may only happen with large values for the z-index. I had some of mine over 100

**Comment by topless** [comment]
I didn't experience that either and I as far as I am aware bootstrap classifies `z-index` of its elements like 1000, 1010, 1020, but I see also its part of `cssnano` optimizations, nice catch, what os were you developing on if you don't mind?

**Comment by dhstack** [comment]
Windows 10

**Comment by dhstack** [comment]
Since this is now merged, I'm closing this issue.
