### ISSUE TITLE
Python instances are always hang after some runs

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#497]
Not sure what can be fixed or done.. but many times after a few runs/deployments the only way to recover is to kill all the Python instances.

(OS X)

**Comment by mdxs** [comment]
Didn't observe that in Xubuntu LTS, used as guest VM under VMware on Windows 8.1

**Comment by topless** [comment]
I think it occurs when you switch branches.

**Comment by mdxs** [comment]
If you switch branches you should have a license to kill ;-)

**Comment by topless** [comment]
Till we figure this one out I have added this to my .bashrc_aliases
```
alias kill_dev='ps aux | grep -i dev_appserver.p[y] | awk '\''{print $2}'\'' | xargs kill -9'
```
To clean up the orphans, with few keystrokes.

**Comment by lipis** [comment]
`killgae` ^^

**Comment by topless** [comment]
Call it whatever lets you sleep at night.
