### ISSUE TITLE
The linkedin login is not working - though that might be because of a linkedin block on appengine

### ISSUE THREAD

**Issue by pardeepkullar** [gae-init/gae-init#500]
I've used GAE boilerplate by coto and i'm testing this one out. Currently the ability to Login via linkedin is not working on Coto or this boilerplate. I guess it is because linkedin has blocked appengine (they've done it before). I've notified them but anyone else who wants to contact them, just tag linkedin on a new stackoverflow question as that is the only place they offer support. The more the better.

**Comment by topless** [comment]
Nice catch,

We get `Invalid response from linkedin`
```
flask.session['access_token'] = (response['access_token'], '')
TypeError: sequence index must be integer, not 'str'
```
 I will look into it, tomorrow.

**Comment by pardeepkullar** [comment]
I think you can ignore it because I've got a message from the Linkedin team saying they do see a problem and it is on their side. They're trying to fix it.

**Comment by lipis** [comment]
Maybe they were busy spamming people with more notifications :)

**Comment by lipis** [comment]
Works already: https://gae-init.appspot.com/signin/linkedin/
