### ISSUE TITLE
npm install - error

### ISSUE THREAD

**Issue by ynotlim** [gae-init/gae-init#509]
Hi ~~GAE-init~~ gae-init team,

I'm trying to deploy the app locally on my Windows 10 machine but getting the following error.  Do you have any idea what is wrong?  The screen says that bower is not a recognized command but the command works fine.

Thanks in advance!

![unnamed](https://cloud.githubusercontent.com/assets/3355351/15200442/cf71575e-17b4-11e6-91df-859a0524aca2.png)

[npm-debug.txt](https://github.com/gae-init/gae-init/files/260406/npm-debug.txt)

**Comment by lipis** [comment]
Can you post here your `bower.json` as well?

**Comment by topless** [comment]
To hack it for now, try installing bower globally, `npm install -g bower`

**Comment by ynotlim** [comment]
I thought I installed it globally already but after re-installing it again, it finally went through.  Thanks for the help!
