### ISSUE TITLE
error when trying to deploy to application

### ISSUE THREAD

**Issue by ynotlim** [gae-init/gae-init#510]
I'm getting this error when trying to deploy my application.  Any ideas why this error is coming up?  No issues when running it locally.

Thanks in advance!

![capture](https://cloud.githubusercontent.com/assets/3355351/15266128/296cbbe4-1969-11e6-8bdc-1e8fbeb8530c.PNG)

**Comment by lipis** [comment]
is it the latest gcloud?

**Comment by ynotlim** [comment]
yeah, latest gcloud.  I was able to fix it by changing `main/*.yaml `to `main/app.yaml`  may be a Windows issue.

**Comment by ynotlim** [comment]
with this update should build.cofffee now be?

```
cmd: "gcloud preview app deploy main/index.yaml #{options_str}"'
cmd: "gcloud preview app deploy main/app.yaml #{options_str}"'
```

**Comment by lipis** [comment]
but there are also `queue.yaml`, `cron.yaml` (maybe more 😕).. so that's why it was `*.yaml`... we'll have to check the general solution for Windows if that's the case..

**Comment by lipis** [comment]
but it's also the `queue.yaml`

**Comment by ynotlim** [comment]
FYI... I tried it on powershell and cmd, same error

```
c:\Users\limtc\Documents\GitHub\gae-init\main>gcloud preview app deploy *.yaml
ERROR: File [*.yaml] not found.
ERROR: (gcloud.preview.app.deploy) Errors occurred while parsing the App Engine app configuration.

```

**Comment by lipis** [comment]
might file a bug for gcloud :)

**Comment by dhstack** [comment]
I'm having this same issue on Windows 10

**Comment by dhstack** [comment]
@ynotlim proposed fix in build only appears to be updating whichever .yaml file is last on the list.

So,

```
cmd: "gcloud preview app deploy main/index.yaml #{options_str}"'
cmd: "gcloud preview app deploy main/app.yaml #{options_str}"'
```
only updates app.yaml. If you switch it, only index.yaml is updated.

**Comment by lipis** [comment]
Maybe
```bash
gcloud preview app deploy main/app.yaml main/index.yaml #{options_str}
```

**Comment by akashawasthi** [comment]
[This](https://cloud.google.com/appengine/docs/flexible/java/dev-java-only#deploying_your_app) (under a _Java_ doc) advises to deploy any _optional_ configuration files separately. I guess it makes some sense intuitively.
>
> If you are using any of the optional configuration files (`index.yaml`, `cron.yaml`, and `dispatch.yaml`) be sure to **deploy them separately** with the `gcloud` command, for example:
> `gcloud app deploy cron.yaml`
> 

Even though the `*.yaml` construct breaks only in Windows, perhaps on _all platforms_ `gulp deploy` should only deploy `app.yaml` leaving others to be updated manually, when required.

i.e., change the [build script](https://github.com/gae-init/gae-init/blob/master/gulp/tasks/build.coffee#L31):
from `cmd: "gcloud app deploy main/*.yaml#{options_str}"`
to `cmd: "gcloud app deploy main/app.yaml#{options_str}"`

**Comment by lipis** [comment]
#588
