### ISSUE TITLE
how to add custom .js and .css files ?

### ISSUE THREAD

**Issue by robelwaka** [gae-init/gae-init#514]
how to add custom .js and .css files ?

**Comment by lipis** [comment]
For custom styles there is also a how to: http://docs.gae-init.appspot.com/howto/#add_styles

**Comment by lipis** [comment]
Related.. #520

**Comment by lipis** [comment]
You can find the related sections in the docs now

- http://docs.gae-init.appspot.com/howto/#add_styles
- http://docs.gae-init.appspot.com/howto/#add_scripts
