### ISSUE TITLE
Building scripts for production.

### ISSUE THREAD

**Issue by topless** [gae-init/gae-init#522]
It looks like when we use a couple more javascript libraries, the build time increases dramatically, more than a minute. Smells exponential .. 

![screen shot 2016-06-02 at 14 48 59](https://cloud.githubusercontent.com/assets/230805/15745274/49477702-28d1-11e6-8fc5-7695cbe56691.png)

**Comment by gmist** [comment]
OMG - 2.5Mb of the minified libs

**Comment by topless** [comment]
I used $uglify mangle: false, due to one of the libs.

**Comment by lipis** [comment]
Not sure if we can do anything here.. the good news is that it's part of the production build so at least you don't wait 2 minutes on every change :P

**Comment by topless** [comment]
For sure, without mangling it drops to 1.7MB, and I cannot selectively mangle only the problematic `lib`. Plotly is the one which is causing me all the hassle.

**Comment by lipis** [comment]
It's quite a lib.. so no doubt it takes some time.. https://github.com/plotly/plotly.js/tree/master/dist

**Comment by gmist** [comment]
@topless you are using SSD or HDD? Maybe try to your project on the [RAM disk](https://www.tekrevue.com/tip/how-to-create-a-4gbs-ram-disk-in-mac-os-x/)?

**Comment by topless** [comment]
SSD, the Ram disk is a very interesting approach.

**Comment by lipis** [comment]
@topless I think we can close that one..
