### ISSUE TITLE
ImportError: No module named msvcrt

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#526]
Because [Click](http://click.pocoo.org/5/) was added to Flask 0.11 for the [New Command Line Interface](http://flask.pocoo.org/docs/0.11/cli/), and Click imports the Windows only module [msvcrt](https://docs.python.org/2/library/msvcrt.html), and the cloud devserver doesn't contain this module, an import error is thrown.

![image](https://cloud.githubusercontent.com/assets/2013388/15913823/3b48f59e-2d91-11e6-8442-c79248d82e3c.png)

I'll create a PR with the workaround I adapted from [this Stackoverflow question](http://stackoverflow.com/a/25915535/2943925).

**Comment by dhstack** [comment]
These are all the file locations that Click tries to import or use msvcrt

![image](https://cloud.githubusercontent.com/assets/2013388/15914088/e95477b6-2d92-11e6-9f2c-b0f192888bee.png)

**Comment by pvlele** [comment]
appengine_config.py


import os
import sys

if os.environ.get('SERVER_SOFTWARE', '').startswith('Google App Engine'):
  sys.path.insert(0, 'lib.zip')
else:
  if os.name == 'nt':
    os.name = None
    sys.platform = ''

  import re
 # from google.appengine.tools.devappserver2.python import stubs
  from google.appengine.tools.devappserver2.python.runtime import stubs

  re_ = stubs.FakeFile._skip_files.pattern.replace('|^lib/.*', '')
  re_ = re.compile(re_)
  stubs.FakeFile._skip_files = re_
  sys.path.insert(0, 'lib')
sys.path.insert(0, 'libx')


def webapp_add_wsgi_middleware(app):
  from google.appengine.ext.appstats import recording
  app = recording.appstats_wsgi_middleware(app)
  return app
this solved my problem

**Comment by mdxs** [comment]
@pvlele Could you edit your comment and use code quotes to preserve formatting?
