### ISSUE TITLE
Clicking on some headers to sort list of models results in 500 error

### ISSUE THREAD

**Issue by jakedotio** [gae-init/gae-init#528]

**Comment by jakedotio** [comment]
Fields affected:

Title Property	
User Authentication
Only for Admins
Properties

**Comment by lipis** [comment]
are you talking about the result when you are deploying the app?! If that's the case it's because there are no indexes..

**Comment by jakedotio** [comment]
No, in magic. See attached screenshot. Clicking on that heading results in a 500 error.
![screen shot 2016-06-22 at 6 30 23 pm](https://cloud.githubusercontent.com/assets/2325504/16286009/9845256c-38a7-11e6-8ef7-58753b74ad7d.png)

**Comment by lipis** [comment]
Removed sorting for those fields.. you can just sort now by name and rank..
