### ISSUE TITLE
No module named jinja2 on local

### ISSUE THREAD

**Issue by dovy** [gae-init/gae-init#531]
OSX Yosemite
Using Pyenv

All requirements properly installed. When running gulp I get the following:
```
Traceback (most recent call last):
  File "/Users/dovy/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/dovy/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/dovy/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/dovy/Development/Sites/wpuptodate.io/io-t/main/main.py", line 3, in <module>
    import flask
  File "lib/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: No module named jinja2
```

Now jinja2 IS installed, but it's installed within the google directory outside of the environment. Checked the permissions, so that's not it.

I've reinstalled the gcloud app. Installed the appengine code, and done everything else I can think of. I can't get this to run locally.  :(

Here's my $PATH
```
/Users/dovy/google-cloud-sdk/bin:/Users/dovy/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/lib/dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-update1/bin:/Users/dovy/.dnx/bin:/Users/dovy/.rvm/gems/ruby-2.2.1/bin:/Users/dovy/.rvm/gems/ruby-2.2.1@global/bin:/Users/dovy/.rvm/rubies/ruby-2.2.1/bin:/Users/dovy/go/bin:/Users/dovy/.pyenv/shims:/Applications/MAMP/bin/php/php5.6.10/bin:/Applications/MAMP/bin/php/php5.6.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dovy/.rvm/bin
```

Any help would be greatly appreciated.

**Comment by dovy** [comment]
Well, found a work around...

Move the embedded copy of jinja2 within the google-cloud-sdk:
```
mv /Users/dovy/Downloads/google-cloud-sdk/platform/google_appengine/lib/jinja2-2.6 /Users/dovy/Downloads/google-cloud-sdk/platform/google_appengine/lib/jinja2-2.6-old
```

Then while NOT in the virtual environment install jinja2.
```
pip install jinja2
```

Now it works. *sigh*

The deep linking within the gcloud config is the problem here.

**Comment by lipis** [comment]
If you run Python from command line.. can you `import jinja2`?

```
$ python
>>> import jinja2
>>>
```

maybe installing it using `pip install jinja2`

**Comment by topless** [comment]
Follow the highest voted [answer](http://stackoverflow.com/questions/18944345/importerror-no-module-named-jinja2?answertab=votes#tab-top) 💯

**Comment by lipis** [comment]
lol

**Comment by dovy** [comment]
Still doesn't work unless I go into the actual environment and install jinja2 manually.  :(

Just cloned and retried. WEIRD.

**Comment by gmist** [comment]
Try to run:
```shell
gulp clean:venv
gulp pip
cat temp/venv/lib/python2.7/site-packages/gae.pth
```
```cat``` output should display the following text
```shell
/opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/google_appengine
/Users/<<username>>/Develop/appengine/five-studio2/main/libx
import dev_appserver; dev_appserver.fix_sys_path()
```
if that's all right check your app.yaml, it must contain:
``` yaml
libraries:
- name: jinja2
  version: latest
```

**Comment by dovy** [comment]
@gmist can you get on slack?

**Comment by dovy** [comment]
FYI, now getting errors with markupsafe that I globally installed jinja2.

It seems like everything gcloud installs that I don't have installed globally is failing.

**Comment by dovy** [comment]
I am now 99% sure this whole issue is related to me using pyenv.  :(

**Comment by gmist** [comment]
Ok, try to run:
``` shell
cd <project_dir>
source temp/venv/bin/activate
pip list
```
what do you see?

**Comment by dovy** [comment]
```
pip list
aniso8601 (1.1.0)
antlr-python-runtime (3.1.1)
blinker (1.4)
click (6.6)
Flask (0.11.1)
Flask-Login (0.3.2)
Flask-OAuthlib (0.9.2)
Flask-RESTful (0.3.5)
Flask-WTF (0.12)
itsdangerous (0.24)
Jinja2 (2.8)
MarkupSafe (0.15)
marshmallow (2.7.3)
oauthlib (1.1.2)
pip (8.1.2)
PyAMF (0.6.1)
python-dateutil (2.5.3)
pytz (2016.4)
requests (2.10.0)
requests-oauthlib (0.6.1)
setuptools (23.0.0)
six (1.10.0)
Unidecode (0.4.19)
webapp2 (2.5.2)
webargs (1.3.3)
WebOb (1.2.3)
Werkzeug (0.11.10)
wheel (0.29.0)
WTForms (2.1)
```

Persistant error:
ImportError: No module named jinja2

**Comment by gmist** [comment]
GAE do not support [Jinja2 2.8](https://cloud.google.com/appengine/docs/python/tools/built-in-libraries-27). What do you have in requirements.txt?

**Comment by dovy** [comment]
And the winner is @gmist.

I haven't changed a thing, but when it went into pip and installed Jinja2 2.6 it worked without a flaw.

```
source temp/venv/bin/activate
pip uninstall jinja
pip install 'jinja==2.6'
```

I tried modifying the requirements.txt, but that didn't work. So I just have to do a little work on each clone.  ;)

**Comment by gmist** [comment]
```pip install 'jinja==2.6'``` - this is not necessarily because Jinja2 already exists in GAE.

**Comment by dovy** [comment]
It fails when run through cloud. I have to install it.

**Comment by lipis** [comment]
@dovy Is it solved?

**Comment by dovy** [comment]
Solved if every time I want to run gae-init locally I run:
`source temp/venv/bin/activate`

Then we're good.  :)

**Comment by lipis** [comment]
You have a very special installtion.

**Comment by dovy** [comment]
Nope, using pyenv. Not too special.  ;)

Might want to put something in the docs.

**Comment by gmist** [comment]
@dovy you can add this command in ```run.py```:
<img width="320" alt="screen shot 2016-06-20 at 20 39 20" src="https://cloud.githubusercontent.com/assets/47926/16204357/805ade70-372f-11e6-9d7c-3f63625bf762.png">

**Comment by dovy** [comment]
Oh that would be beautiful.  ;) Will do so.

**Comment by dovy** [comment]
@gmist Like a dream. Bless you.
