### ISSUE TITLE
Extending the User Model

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#544]
Hi,

I am trying to extend the User model, so that when a user is signing up, they are required to give additional information before they can register an account. I have created the form with all of the fields, but whenever I hit submit, there is a message saying "The response parameter is missing". What does this mean? Thanks.

**Comment by lipis** [comment]
We might need some code to say more.. but most likely you forgot the [`csrf_token`](https://github.com/gae-init/gae-init/blob/master/main/templates/profile/profile_update.html#L6)

**Comment by charleswson** [comment]
I've updated the user model to include the additional entities that I want, as well as FIELDS at the bottom of user.py. I've then added those entities to the signup_form.html document, and the function signup() in auth.py. Do I need to alter the way they are submitted? I can't seem to format the code properly here, but I can send it on Slack if that would be useful.

**Comment by lipis** [comment]
still no clue what's wrong.. post code using the ``` or if it's too long better use https://gist.github.com/

**Comment by charleswson** [comment]
Apologies that I still haven't made it clear. Here are the gists:

[https://gist.github.com/charleswson/782c6d496acdd5b86d99f7a4a943318e](url)
[https://gist.github.com/charleswson/b054eb1d0007e3f75fb9d0d20b2f70d3](url)
[https://gist.github.com/charleswson/32273840bae5c14526f0390a39527be8](url)

**Comment by lipis** [comment]
It must be the reCAPTCHA thing.. you will have to set it up properly.. I would suggest you to remove it first to see that everything else is working and add it again..

**Comment by charleswson** [comment]
Perhaps it's just me, but still no luck.

**Comment by lipis** [comment]
Usually 500 have more info.. either from the dashboard or in the terminal.. that's very generic.

**Comment by charleswson** [comment]
The error is "BadValueError: Entity has uninitialised properties". Do you know what this suggests?

**Comment by lipis** [comment]
You have required properties that you didn't initialize..

**Comment by charleswson** [comment]
Thank you. What would be the best way to fix this problem?

**Comment by lipis** [comment]
to initialize them... or remove the `required=True`..

**Comment by charleswson** [comment]
Thank you - how do I go about initialising them?

**Comment by lipis** [comment]
When you are about to create them you need to explicitly give them value

```
entity_db = Entity(stuff='foo', more='bar')
```

if `stuff` is required and you skip it, you will get this error message.. so in short I think you added/combined bunch of things and things started breaking.. try to dig in with less stuff.. for example remove all the required fields from the extra properties that you added.. maybe having only one extra property, etc..

**Comment by charleswson** [comment]
Thank you very much.
