### ISSUE TITLE
 InvalidSenderError: Unauthorized sender

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#545]
I am getting the above error whenever my application tries to send a verification email, and the email is not sending. How do I go about resolving this issue? Many thanks

**Comment by lipis** [comment]
The feedback email which is the sender's email has to be authorized.. you need to add it to the list from the permissions settings on App Engine or use your own

**Comment by charleswson** [comment]
Thank you, also I believe that is already the case. I am using the email address for the feedback email which is also set as the Owner's email address for the project. Does it need to be specifically added as a service account?

**Comment by lipis** [comment]
It looks like it works here: https://gae-init.appspot.com/signup/ so I'm not sure what's the issue.. also you might need to restart the instances if you changed the email recently..

**Comment by charleswson** [comment]
I think I might have fixed that issue, but now I appear to be over the quota for a free account, so I'll add a billing account. Thank you very much.

**Comment by lipis** [comment]
yes they changed recently the free quotas limits..
