### ISSUE TITLE
Adding gcloud-python doesn't work

### ISSUE THREAD

**Issue by kmevissen** [gae-init/gae-init#559]
I've tried adding gcloud-python in the requirements, but when running gulp or gulp deploy this results in a DistributionNotFound exception.

On production App Engine this seems related to the lib.zip file. The **init**.py in gcloud package is making a call to pkg_resources, but it's unable to find the gcloud package:

from pkg_resources import get_distribution
**version** = get_distribution('gcloud').version

When uploading the lib folder unzipped this works fine, this is my workaround for now.

**Comment by lipis** [comment]
You are not suppose to add that to the requirements.. why would you do that?!

**Comment by kmevissen** [comment]
Because I'd like to use the PubSub and BigQuery SDKs from the gcloud-python package.

**Comment by lipis** [comment]
For some reason I thought that you were trying to install the dev env via requirements.

Try adding `gcloud==0.18.1` into the requirements. It looks like they might change the name from [`gcloud`](https://pypi.python.org/pypi/gcloud) to [`google-cloud`](https://github.com/GoogleCloudPlatform/google-cloud-python)

**Comment by kmevissen** [comment]
Ah, sorry if I wasn't clear enough :)

Yes that's actually what I've done, so added gcloud==0.18.1 to my requirements.txt , and did an import in welcome.py. Then ran npm install and gulp, but this results in a DistributionNotFound exception. When doing a gulp deploy this also results in the same exception in Production.

Then locally, running pip install -r requirements -t main/lib --upgrade resolves the issue locally and no DistributionNotFound exception occurs anymore. This might be related to the copy task that copies packages to lib folder, but I haven't really dug into this (the manual pip command fixes it for me at the moment...)

However, that doesn't fix the deployment, in the cloud it's still throwing the same error, and I've worked around it by including the full lib folder.

It seems specific to the gcloud package, as importing other packages work fine, so not sure if it's worth fixing it. Also that rename might indicate it gets added to the Google App Engine SDK at some point.

**Comment by lipis** [comment]
That should be related.. https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1893 Don't have much time now to test things out, but some clues might be there :)

**Comment by mdxs** [comment]
Is this still an issue?

**Comment by lipis** [comment]
Will close it for now..
