### ISSUE TITLE
Python throws an exception when deploying on macOS Sierra.

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#574]
I recently upgraded to macOS Sierra (10.12) and since that moment I couldn't deploy anything since my Python was throwing this error: 

https://gist.github.com/lipis/946c17457cdd8acf45d6270091ebc63a

After a long discussion that started for a [different reason](https://github.com/Homebrew/brew/issues/1171) and since I tried whatever I could.. I decided to have a clean/fresh installation of Sierra.. After installing only the very basic ones, unfortunately I'm getting exactly the same error when I'm trying to:

```
gcloud app deploy main/app.yaml --project ...
```

Is it only me?!

- macOS 10.12
- Python 2.7.12 (Homebrew)
- Google Cloud SDK 128.0.0
- app-engine-python 1.9.40
- Latest Command Line Tools (Installed the beta ones as well for testing) 

<img width="433" alt="screen shot 2016-10-02 at 10 57 56" src="https://cloud.githubusercontent.com/assets/125676/19019658/3bcce80a-888f-11e6-8845-c5409f236d20.png">

<img width="781" alt="screen shot 2016-10-02 at 10 58 33" src="https://cloud.githubusercontent.com/assets/125676/19019657/38e4dce2-888f-11e6-8e44-60bfda8f555e.png">

**Comment by rbubley** [comment]
Are you expecting all those python processes or is that a symptom?

**Comment by lipis** [comment]
a bad symptom..

**Comment by gmist** [comment]
Unfortunately I use 10.10.5 and 10.9.5, so I can not reproduce it. Try to complete remove all venv stuff (gulp clean:venv, rm -rf main/lib, etc).

P.S. a good time to try [it](https://github.com/gae-init/gae-init/pull/550) :)

**Comment by rbubley** [comment]
You've probably gone this route, but presumably the parent PIDs give a clue as to what is spawning them all. Thought that might give a clue if the problem is with the python binary or something calling it.

**Comment by lipis** [comment]
@gmist I burned everything to the ground (`git clean -fdx`) but no luck..  btw.. I actually tried docker a while ago and it works.. and I'll come back to it soon.. but it's not feasible at the moment to upgrade all the projects to that :/

@rbubley Not much.. when I'm killing the process this is what is being thrown in the console..

```
/Users/lipis/google-cloud-sdk/bin/gcloud: line 115:  6129 Terminated: 15          "$CLOUDSDK_PYTHON" $CLOUDSDK_PYTHON_ARGS "${CLOUDSDK_ROOT_DIR}/lib/gcloud.py" "$@"
/Users/lipis/google-cloud-sdk/bin/gcloud: line 115:  6522 Terminated: 15          "$CLOUDSDK_PYTHON" $CLOUDSDK_PYTHON_ARGS "${CLOUDSDK_ROOT_DIR}/lib/gcloud.py" "$@"
/Users/lipis/google-cloud-sdk/bin/gcloud: line 115:  5918 Terminated: 15          "$CLOUDSDK_PYTHON" $CLOUDSDK_PYTHON_ARGS "${CLOUDSDK_ROOT_DIR}/lib/gcloud.py" "$@"
```

and my `ps -ex` looks like this with the relevant lines: https://gist.github.com/lipis/4eb26a72098560f7539c3ad697ff5ddb

**Comment by lipis** [comment]
I found the root of the cause and it's the file `lib.zip`.

When that file is present (regardless of the size) I'm getting this exception thrown.. when the file is missing everything goes well.. (except the fact that the deployed app won't work without it)

I also tried to downgrade to different versions (116, 118, 120), but I'm still getting the same error when the `lib.zip` is present.. anyone with more clues?!

**Comment by lipis** [comment]
It looks like I'm not the only one.. https://code.google.com/p/googleappengine/issues/detail?id=13304

**Comment by lipis** [comment]
It works now.. :)
