### ISSUE TITLE
Microservices appengine gae-init

### ISSUE THREAD

**Issue by edmiranda** [gae-init/gae-init#586]
Hi,

I wanted to know if your project have the capacity of implement microservices appengine?

Thanks for help ous with your solutions.

**Comment by lipis** [comment]
It depends on what exactly you want/mean by microservices.. but it's definitely possible. Can you describe the use case on a high level?

**Comment by edmiranda** [comment]
Thanks for your answer, I solved with this https://cloud.google.com/appengine/docs/python/microservices-on-app-engine .

**Comment by lipis** [comment]
Yep: https://github.com/gae-init/gae-init/blob/master/main/app.yaml#L1 :)
