### ISSUE TITLE
"None" project name on fresh project

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#587]
When starting a new project, the branding is "None".

This is fine for me since I'm familiar with how gae-init works (just need to update the admin settings), but this may be confusing for new users. Maybe put "Your Brand Here" instead of "None" to make it clear it can be replaced.

![image](https://cloud.githubusercontent.com/assets/2013388/19708853/9766bfd4-9ad6-11e6-803e-00ade1a9601d.png)

**Comment by topless** [comment]
In the `main/model/config.py` when we create the model we initialise `brand_name` as
`brand_name = ndb.StringProperty(default=config.APPLICATION_ID)`
and because we run it locally, in `main/config.py` there is no APPLICATION_ID.
We can do something like `APPLICATION_ID = app_identity.get_application_id() or 'gae-init'`
in `main\config.py`.

**Comment by mdxs** [comment]
Doesn't https://github.com/gae-init/gae-init/blob/master/main/config.py#L14 catch this?  Or is it the running locally part that skips this?

**Comment by lipis** [comment]
The application was removed from `app.yaml` there is no way of knowing the app name locally.. I just don't want to add something that will be definitely removed.. we'll see how we are gonna deal with that one..

**Comment by mdxs** [comment]
deal with that one.. or: deal with that None

**Comment by mdxs** [comment]
Guess you have similar concerns about changing https://github.com/gae-init/gae-init/blob/master/main/model/config.py#L18 to:
  `brand_name = ndb.StringProperty(default=config.APPLICATION_ID or 'Your Brand Here')`

**Comment by lipis** [comment]
Wherever we are going to put it.. it still going to be confusing as once they are going to replace the placeholder the deployed version will show something else..

**Comment by rbubley** [comment]
In many sorts of documents, The convention for text that is to be replaced is to enclose it in square brackets. So this would suggest a default value of "[Brand name]".

It seems rather redundant to rely on on the name in the yaml file: so many other configuration parameters have to be specified on the configuration page, why have a special case for this one?

There is also an argument for putting it directly in somewhere as a python variable - it seems a bit unnecessary to have a data store query for static data that does not need to be held privately (as distinct from passwords, api keys, etc.)

**Comment by dhstack** [comment]
To prevent confusion, what if it's called "Local Env Brand Name" or something?

**Comment by lipis** [comment]
Actually the `app_identity.get_application_id()` returns `'None'` (string) so we have to do more mambo/jumbo to avoid it. So I will close it for now.. as it works as expected when deployed..
