### ISSUE TITLE
[Windows] GAE deploy error when using wildcard

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#588]
Not sure if this is only a Windows thing, but using a wildcard for the filename when deploying doesn't make gcloud happy.

![image](https://cloud.githubusercontent.com/assets/2013388/19713470/46b17988-9afb-11e6-9388-627e801a2774.png)

Replacing this line in `build.coffee` solves the issue
`cmd: "gcloud app deploy main/*.yaml#{options_str}"`
with
`cmd: "gcloud preview app deploy main/app.yaml main/index.yaml#{options_str}"`

This isn't optimal as it won't deploy all the .yaml files (index, cron, etc)

I'm using the latest builds of gae-init and google cloud sdk.

**Comment by JustinWenzhaoLi** [comment]
Hi David!

I am Justin, a Chapman student advised by Dr. El-Askary, I am currently studying your apsimRegion code but I had some problems running it. I tried to run it following the tutorial.rst, but I did not make it, could you provide some help? 
my email is li276@mail.chapman.edu
Best,
Justin wenzhao Li

**Comment by lipis** [comment]
There are also other things like `cron.yaml` and `queue.yaml` (if not more..).. I guess there is no way to have some sort of wildcard here..

**Comment by lipis** [comment]
We could post an issue on GAE directly..

**Comment by dhstack** [comment]
That's a good idea. I can post the issue - what's the correct url for the GAE repo?

**Comment by lipis** [comment]
https://code.google.com/p/googleappengine/issues/list

 would be awesome..

**Comment by lipis** [comment]
Post it here when you are done..

**Comment by dhstack** [comment]
https://code.google.com/p/googleappengine/issues/detail?id=13393

**Comment by mdxs** [comment]
Think this issue can be closed; surely lots has changed since 2016... so doesn't seem productive to try and look into this.
