### ISSUE TITLE
why not use application factories as described in flask documentation

### ISSUE THREAD

**Issue by chavz** [gae-init/gae-init#592]
I'm kinda new to google app engine and stuff, but I've been working with python and flask for few years now, and I'm just wondering, since this looks like a well maintained and very active project, why isn't it using [application factories as describe in the flask documentation](http://flask.pocoo.org/docs/0.11/patterns/appfactories/) ?? I mean I've always thought that's kind of the defacto standard. Don't know though if it has anything to do with being run in GAE.

**Comment by lipis** [comment]
It started like that to keep it simpler and there was one test by @gmist but not maintained.. At the moment there are quite a few dependencies on that project and that change will potentially break bunch of things (and hearts).. ;)

**Comment by chavz** [comment]
I see, anyway could you direct me to that "one test" by @gmist  you were talking about, i'm currently having problems in creating tests see #594, perhaps that could be some help.

**Comment by lipis** [comment]
That one test is long gone :( sorry..
