### ISSUE TITLE
Use official vendor library instead of sys.path manipulation

### ISSUE THREAD

**Issue by theacodes** [gae-init/gae-init#596]
https://github.com/gae-init/gae-init/blob/master/main/appengine_config.py uses sys.path manipulation which doesn't always work correct, suggest using `google.appengine.ext.vendor` that handles `lib` as a site-packages directory.

**Comment by gmist** [comment]
In which cases it's not working correctly?

**Comment by jonparrott** [comment]
Notably vendor handles namespace packages correctly.

**Comment by rbubley** [comment]
This is still an issue with the way libraries are added in gae-init: there is an implicit assumption in the logic that where the package exists, new sub-packages cannot be added, so, for example, if you do try to load google-cloud-XXX, you end up with the code deciding not to upload it, as 'google' would be shadowed.

**Comment by lipis** [comment]
So what do we do?

**Comment by rbubley** [comment]
I haven’t had time to look at this recently. If I recall correctly, it would be much simpler to proceed if we abandoned lib.zip in favour of an uncompressed lib directory. But the rationale for the current code base logic was eluding me.
