### ISSUE TITLE
Changes to config.coffee do not result in script/ext.js being rebuilt

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#598]
Workaround is to stop and restart gulp.

**Comment by lipis** [comment]
yes.. that's known.. :/

**Comment by rbubley** [comment]
Ah. Perhaps in the interim, mentioning this in [the "How To"](http://docs.gae-init.appspot.com/howto/#add_frontend) would be useful.

**Comment by lipis** [comment]
Could be a good idea.. (or solving it.. hehe)

By the way.. is the rest in the "How To" up to date? or things changed?! (out of the office these days)
