### ISSUE TITLE
Magic code not robust to model changes

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#602]
If you update a magic model in-place, you can end up having required properties in the database that are not initialized.

Various of the templates in magic will fall over, with
`BadValueError: Entity has uninitialized properties: YYY_key`

This comes from templates with statements like 
`XXX_db.YYY_key.get().name if XXX_db.YYY_key else ''`

**Comment by rbubley** [comment]
It's not hard to trap these errors using a utility function with a try/except block.

**Comment by lipis** [comment]
I think it would better to add the default value if it's a required property when doing updates.. or better having some sort of batch admin script that updates the older entities. (If I understood correctly the issue)

**Comment by rbubley** [comment]
That would work, too. Example of how to do it this way - https://cloud.google.com/appengine/articles/update_schema

**Comment by trickidicki** [comment]
+1 this.
I am generating quite a large relational model and ran into this issue straight away when using Magic. Made the entire experience a little less ... magical?

**Comment by lipis** [comment]
There is not much we can do about it I guess..
