### ISSUE TITLE
SSLError: [Errno 185090050] _ssl.c:357: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

### ISSUE THREAD

**Issue by Viktour19** [gae-init/gae-init#604]
When using ssl and custom domain (not sure this has any impact), an https request gives this warning

InsecurePlatformWarning: A true SSLContext object is not available.

and then a subsequent error

SSLError: [Errno 185090050] _ssl.c:357: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

[full log](https://gist.github.com/Viktour19/37b85199c2272f42891885c2f063f29f)

**Comment by lipis** [comment]
Not sure if that has anything to do with gae-init..
