### ISSUE TITLE
Cron jobs with gae-init

### ISSUE THREAD

**Issue by iirubio** [gae-init/gae-init#606]
I am trying to use cron jobs with gae-init but I can't seem to get it right, I've looked at google's documentation and stackoverflow posts, but in all of them they explicitly define the handlers. 
In my app.yaml I leave this url:

- url: /.*
  script: main.app
  secure: always
  redirect_http_response_code: 301

I have a dashboard.py file which manages some of the routes in the web app and it works fine. 
I was trying to do a cron of:
@app.route('/dashboard/test/', methods=['GET'])
def dashboard_test():

by defining in the cron.yaml:

cron:
- description: scrape xml
  url: /dashboard/test
  schedule: every 1 minutes

I don't know what I'm doing wrong, it gives a error 500 in the cron job manager for development. I've find this in gae-init documentation: @auth.cron_required. I tried it with the same setup I had but looks like I'm doing something wrong, or I don't really need that decorator. 
Thanks in advance

**Comment by lipis** [comment]
Are you using custom domain with https?

**Comment by iirubio** [comment]
No, I'm using the one gae gives with https.
When testing cron I tried the route '/' and with that one, in development, the cron job admin showed success. But I can't get to work any other url.

**Comment by GateCrash3r** [comment]
Hi iirubio,

Try adding this to your app.yaml:

- url: /dashboard/test
  script: main.app
  login: admin

I think it parses these handlers from top to bottom, so try adding it right below the 

`handlers:`

line.

**Comment by iirubio** [comment]
It throws a 302 error code. I'm looking for an answer of why that is happening now.

**Comment by xshibux** [comment]
if the route has a / at the end
@app.route('/dashboard/test/', methods=['GET'])

and you defined it without you will get a redirect.
- url: /dashboard/test
  script: main.app
  login: admin

These slashes should match.

**Comment by iirubio** [comment]
Ok, I solved the problem. I didn't know that while using cron I had to not only give a handler but a template for the url, and a render function of that url. Given the cron isn't supposed to be rendering anything I didn't think it was neccesary. Thanks for the help! You can close the thread.

**Comment by lipis** [comment]
it just has to return a `200` so you don't really need a template or something.. but a simple `return 'OK'` is enough.
