### ISSUE TITLE
Custom Packages - Need to delete lib.zip

### ISSUE THREAD

**Issue by xshibux** [gae-init/gae-init#607]
I had created custom package that I wanted to add to the library.  It worked fine on my local development environment but when I deployed it to the app engine I got an ImportError: No module named.  So after some trial an error I noticed that the lib.zip file didn't have my package and decided to delete it and let gulp rebuild it.

Did I do something wrong or did I miss something?

Thanks...

**Comment by lipis** [comment]
how did you deploy?! Did you use `gulp deploy`?

**Comment by xshibux** [comment]
Yes, I used the command found in the docs.

**Comment by NoahWilcox** [comment]
Could you elaborate a bit more? After it was rebuilt, I assume what you are saying is that it did not include your package in the lib.zip file again? You could possibly try to run` npm install` again. Have you tried to vendor it in?

**Comment by xshibux** [comment]
Here are the steps:
1.  Added the custom package
2.  Ran gulp to test locally... everything works fine
3.  Ran gulp deploy to app engine... tested and got an error saying ImportError
4.  Unzipped the local lib.zip file to see what's in there and this is where I noticed that the custom package was missing.
5.  I deleted the local lib.zip file
6.  Ran gulp to test locally... everything works fine again.  This time I check the zip file and the custom package was there.
7.  Ran gulp deploy to app engine now everything worked.

I didn't try vendoring it because it was simple package that was referencing mailgun and was using urlfetch to send out the email.

Shouldn't the gulp scripts take care of this so why would I need to run npm install?

**Comment by NoahWilcox** [comment]
Have you checked the lib directory in /main? It may be working off of your local library. To install a library directly into the app, using terminal from your project directory, you'll want to use `pip install yourPackage -t main/lib/` as opposed to `pip install yourPackage`.

This way, the library will be placed inside of your main/lib directory, and will be included once you deploy.

**Comment by xshibux** [comment]
@NoahWilcox Thanks for the tip.  I had copied the package directly into the main/lib/ folder.  So I expected it to just work.  I'm just wondering if I should have done what you suggested first and if so I didn't see any docs on that.  

I appreciate your feedback/help.

**Comment by NoahWilcox** [comment]
Hmm, that should have been fine. Is ___init___.py inside of your package? If so, and you still are unable to get it to import, you could try adding this in your main/appengine_config.py file:

`from google.appengine.ext import vendor
vendor.add('lib')`

**Comment by xshibux** [comment]
@NoahWilcox well, it's not that I can't get it to import.  

import mypackage #this works fine and I can reference the class.

The issue is that when the lib.zip file is created/updated for deployment on the app engine.  The zip file doesn't have my package.

**Comment by NoahWilcox** [comment]
Ah, that's normal behavior. It only zips the referenced libraries that are in the requirements.txt file. Any other libraries you add directly into the main/lib directory will not be zipped. This however should not create any issues for you after deploying your app. When you deploy, you say that you get an import error, so the solution I mentioned above SHOULD fix it. If not, let me know!

**Comment by gmist** [comment]
Just add your package into ```main/libx```

**Comment by xshibux** [comment]
@NoahWilcox actually that's not true.  After deleting the lib.zip file on disk I ran gulp so it can recreate it.  This time my package was picked up from main/lib folder.  If I unzip the package it's there.  

I think it should always grab everything in the main/lib folder but it's not.

**Comment by xshibux** [comment]
I did

**Comment by NoahWilcox** [comment]
@xshibux That's odd, because I have a large amount of packages in my lib folder and I have never actually seen any of them get compiled into the zip file unless I had added them in the requirements.txt file. These packages are not in the libx folder for me, so this may be where we may differ.

I didn't notice you said you got it to work, so that's great.

@gmist is right though, adding to libx as opposed to lib is the correct way to do it for gae-init. Thanks for teaching me something today gmist!

**Comment by xshibux** [comment]
@gmist I'm sorry i thought you were referring to main/lib.  This might be because I'm on a mac os 10.12.3.  I don't see a main/libx folder.  If you are using a mac could you direct me.

**Comment by NoahWilcox** [comment]
@xshibux The main/libx folder is not there by default (on any OS). You need to create the folder manually.

**Comment by xshibux** [comment]
@NoahWilcox Got it.  I see that when deployed the libx folder is deployed instead of being zipped up into the lib.zip file.  I'm going to close this.

**Comment by vanessa-bell** [comment]
Hi @gmist or @NoahWilcox ... this thread helped me to deploy my GAE project with requests-toolbelt. The way I finally did it is by adding the requests and requests-toolbelt libraries to main/libx. I'm a newbie to Python and GAE so I was wondering if one of you could explain to me WHY this works? Much appreciated!!

**Comment by gmist** [comment]
@vanessa-bell once upon a time it was the only way to add dependencies into your project. Since then much has changed and now dependencies are added through pip + requirements.txt. But the old way is left for compatibility.

**Comment by lipis** [comment]
and for some libraries that don't play good when they are zipped.. `libx` is being uploaded as is, and it't not included in the `lib.zip` file.

**Comment by vanessa-bell** [comment]
Ok, thanks. Makes sense. I gotta say, it would've saved me a lot of time if there was a note somewhere in the documentation about trying to place libs in main/libx if they weren't working in lib.zip (maybe in the Adding a Python Library section) :)
