### ISSUE TITLE
Is there a way to strip bootstrap and font-awesome?

### ISSUE THREAD

**Issue by NoahWilcox** [gae-init/gae-init#612]
I'm looking to strip out bootstrap and font-awesome. Is there a somewhat easy(ish) way to do this? I made my first attempt to just now and it didn't go too well.

**Comment by rubalcava** [comment]
If you're looking to remove the font-awesome icons from a page (like the one in the header for sign in), the simplest way is to just remove the spans with the font-awesome classes. If you want to remove font-awesome entirely, you'll have to change the bower.json file and confirm it isn't a dependency elsewhere.

Bootstrap is the same (removing classes, changing bower.json, checking dependencies), but it won't be as easy as removing font-awesome. You'll have to redo all of the markup to make it look the same, but if that's what you're looking for, that's how you'd do it.

**Comment by lipis** [comment]
Totally agree with @rubalcava. Bootstrap is indeed much harder to remove as you have to edit every single file in templates.

**Comment by lipis** [comment]
There is not much we can do about it.. so I'll close this one :)
