### ISSUE TITLE
purpose behind the `utils.prefetch_link(next_url)` in main/templates/auth/auth.html

### ISSUE THREAD

**Issue by chavz** [gae-init/gae-init#614]
im wondering what might be the purpose behind in requesting the `next_url` asynchronously in the Sign In page _(see below)_, I know it was introduced for the **Email Authentication** (1d2b4f99e1), but I just can't figure out why.

```
<!-- main/templates/auth/auth.html -->

# block head
{{ utils.prefetch_link(next_url) }}
# endblock
```

this is due, mainly because the the project i'm currently working on is kind having trouble with repeating redirect to the sign-in page. Although we are only using google sign in. What happens is that after signing in through google it gets redirected to the signin page again. and based on my finding the culprit is the above code, but since it was from `gae-init`, i'm having second thoughts on just removing it, even though we are not  kind of using it.

**Comment by lipis** [comment]
actually, that could be the root of a lot of evil..! :/ Let's scrap it.. there is no point of prefetching something that requires login.

**Comment by lipis** [comment]
Indeed it was #615 :)

**Comment by lipis** [comment]
Fixed now
