### ISSUE TITLE
gulp doesn't start GAE dev server

### ISSUE THREAD

**Issue by schiluka** [gae-init/gae-init#624]
Followed the instructions on quick start and see all npm and pip modules are installed properly.
However, when I run 'gulp' it frozen at below step and don't GAE dev server or admin server started.

Is there any node/npm/python compatibility here to run?

See this error below:
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
-----
[03:04:24] Finished 'script:dev' after 2.24 s
[03:04:24] Finished 'ext:dev' after 2.28 s
[03:04:24] /<>/main/static/dev/script/script.js reloaed.
[03:04:24] /<>/main/static/dev/script/ext.js reloaded.

Below are the versions
node -v
v0.10.18
npm -v
4.4.2
gulp -v
CLI version 3.9.1
Local version 3.9.1
Python - 2.7

**Comment by mdxs** [comment]
The **Requirements** at http://docs.gae-init.appspot.com/requirement/ specify:

> Download the latest (LTS or current) Node.js and install it globally on your system.

Follow the link under Node.js there and on the Downloads page, LTS shows:

> Latest LTS Version: v6.10.0 (includes npm 3.10.10)

and Current shows:

> Latest Current Version: v7.7.3 (includes npm 4.1.2)

In either case, that is a mismatch with what you have on your system.

**Comment by lipis** [comment]
Yep! Very old versions.. I'll close it and if it still doesn't work after upgrading.. write back to us :)

**Comment by schiluka** [comment]
Thanks, it works fine now with LTS version.
However, it shows None in navigation bar and also header section.

**Comment by lipis** [comment]
That's fine.. you can change the name from Admin Config.. when deployed by default it gets the application name..
