### ISSUE TITLE
use reCAPTCHA invisible instead of reCAPTCHA v2

### ISSUE THREAD

**Issue by felixtfl** [gae-init/gae-init#650]
[reCAPTCHA invisible](https://www.google.com/recaptcha/intro/invisible.html)

**Comment by lipis** [comment]
by the way.. is the current implementation works?! It's been a while since I used reCAPTCHA :)

**Comment by felixtfl** [comment]
it's working well

**Comment by lipis** [comment]
Then at least it's not super urgent.. I'll check it eventually as I don't have much time these days :(

**Comment by mdxs** [comment]
Think this ticket can be closed: without a PR to implement it, it is just a wishlist item at best.
