### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [gae-init/gae-init#651]
Does this project support Python 3?

I think that GAE ist not restricted to Python 2 anymore.

**Comment by gmist** [comment]
Unfortunately [Lightweight Python 2.7 runtime is optimized to scale nearly instantaneously to handle huge traffic spikes](https://cloud.google.com/appengine/docs/python/)

**Comment by Tset-Noitamotua** [comment]
What does that mean? Google defacto promotes usages of Python 2.7? I'm shocked!

Have anybody tried to port this to Python 3 anyway?

**Comment by gmist** [comment]
Of course, you can use the [GAE flexible environment](https://cloud.google.com/appengine/docs/flexible/python/) and Python 3.5, but in most cases it is much more expensive. Gae-Init is made for the [standard environment](https://cloud.google.com/appengine/docs/standard/python/), so we are forced to use Python 2.7

**Comment by Tset-Noitamotua** [comment]
Shame on Google ... Python's inventor works for them ;-)

They would do Python community a favour by updating their standard environment to Python 3.

**Comment by lipis** [comment]
Python inventor works for Dropbox :) and as already mentioned this project is made for standard environment, therefore there are no plans to port it to Python 3 at the moment..

**Comment by giancarlocp** [comment]
and now? for gae-init-7.0

**Comment by giancarlocp** [comment]
and now with the python 2 end?
What [implication](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/) will we have? such as [bundled services](https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrating-services)

**Comment by rbubley** [comment]
The harder bits of the migration are indeed around the bundled services. It would probably be a good idea to open separate issues on the migration of each of the services in use.
