### ISSUE TITLE
firebase auth?

### ISSUE THREAD

**Issue by cloudwizard** [gae-init/gae-init#654]
I am interested in using firebase auth.  Would that be interesting?  If I wrote it, what bits would I need to write for it to integrate properly?

**Comment by cloudwizard** [comment]
https://github.com/klokantech/flask-firebase
change the datamodel is my guess

**Comment by mdxs** [comment]
I'm not sure if such integration based on Flask-Firebase would be easy to do; it appears to me that Flask-Firebase is primarily based on HTML loading Javascript to offer Facebook, GitHub, Google, and Twitter as provider login options (next to an email based one). The main difference from how that can already be done here in gae-init (plus more) is that you would indirectly do this via your Firebase Project and API-key.

Could you explain your goal / expected benefit?

**Comment by lipis** [comment]
I'll close this as there are no plans for such thing..
