### ISSUE TITLE
Google App Engine still NOT FOUND on Windows after installing gcloud and app-engine-python

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#655]

**Comment by bennyn** [comment]
My setup (`gcloud -v`):

```bash
Google Cloud SDK 154.0.0
app-engine-python 1.9.52
bq 2.0.24
core 2017.05.01
gcloud
gsutil 4.25
```

**Comment by lipis** [comment]
after installing the classic version it works.. @gmist maybe it's time to remove and somehow check if the gcloud and `app-engine-python` is installed :|

**Comment by bennyn** [comment]
Yes, when I installed [GoogleAppEngine-1.9.53.msi](https://storage.googleapis.com/appengine-sdks/featured/GoogleAppEngine-1.9.53.msi) it worked!

**Comment by gmist** [comment]
https://github.com/gae-init/gae-init/pull/550 :)

**Comment by lipis** [comment]
@gmist Right :) That's quite a change though.. :/

**Comment by bennyn** [comment]
Is it really necessary to shim out Windows by using a Docker image? 

I mean... It's working now for me with GAE v1.9.53. Python & Node are also cross-platform compatible, so it shouldn't be a big deal to support both worlds (Unix & Windows)? 

But it's just me, a blue-eyed novice, speaking. 😁

**Comment by mdxs** [comment]
@bennyn That makes you perfect as gae-init's Windows support expert ;-)

**Comment by mdxs** [comment]
Think this can be closed; at the time it was reported that things worked again.
