### ISSUE TITLE
localhost:3000 loads before server is ready

### ISSUE THREAD

**Issue by bennyn** [gae-init/gae-init#663]
When working with "gae-init" I realized that the `http://localhost:3000/` page ramps up in my browser even before the Python dev server starts. It would be nice if the page opens once the server is ready because otherwise it will end up in a page which fails to load.

**Screenshot**

![screenshot](https://cloud.githubusercontent.com/assets/469989/26036949/f508512e-38e8-11e7-913e-e8f838c540da.png)

**Comment by mdxs** [comment]
Confirmed: I see the same on Xubuntu 16.04 LTS ever since #639, initially thought it was just me (running my development environment inside a VM).

**Comment by mdxs** [comment]
This can be closed; recently with a Xubuntu 18.04 LTS it seems to work fine. Probably a lot has changed since 2017 and thus this is overtaken by events already.

**Comment by bennyn** [comment]
Ok, thanks for your update.
