### ISSUE TITLE
sleuthing out a FlaskWTFDeprecationWarning

### ISSUE THREAD

**Issue by mroswell** [gae-init/gae-init#665]
I'm still getting:
```
/.../.../main/control/file.py:20: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
```

Does it run automatically because it's in __init__ in form.py, or is this because of something I did while copying the boilerplate from the phonebook tutorial?

I see #578 but note that in that commit, it says 
```
class SignUpForm(flask_wtf.FlaskForm)
```
I think I'm concluding that the tutorial should say FlaskForm instead of form, and I'm not sure why the flask_wtf vs. wtf are different. I have some ideas, and will do a pull request on the tutorial, and you can let me know if it's an accurate one. 

Two changes in the tutorial:
from flask.ext import wtf --> import flask_wtf
class GoalUpdateForm(wtf.Form): --> class GoalUpdateForm(flask_wtf.FlaskForm):

**Comment by mroswell** [comment]
Yes :)

**Comment by lipis** [comment]
Thanks! 🍻 I also deployed the latest changes on docs :)
