### ISSUE TITLE
jinja2 configuration error for amp templates

### ISSUE THREAD

**Issue by cloudwizard** [gae-init/gae-init#680]
In AMP, you need to have css inline.  The problem is if you use a id in the css, jinja2 treats it like a variable.  AMP is accelerated mobile pages.

app.jinja_env.line_statement_prefix = '#'

Is there another character that would not cause problems?

**Comment by mdxs** [comment]
Perhaps... from what I understand you claim this to be a jinja2 with AMP issue. That is: not a gae-init specific issue. So you may want to ask this question in another context like the AMP project,
