### ISSUE TITLE
Front end not loading on local development - change /templates/bit/style.html

### ISSUE THREAD

**Issue by katepark** [gae-init/gae-init#726]
After following set up instructions, styles of front end were not loading locally

Change /templates/bit/style.html so it no longer references dev/style/style.css which does not exist

```
# if config.DEVELOPMENT
  <!-- <link rel="stylesheet" href="/p/dev/style/style.css?{{config.CURRENT_VERSION_ID}}"> -->
  <link rel="stylesheet" href="/p/min/style/style.css?{{config.CURRENT_VERSION_ID}}">
# else
  <link rel="stylesheet" href="/p/min/style/style.css?{{config.CURRENT_VERSION_ID}}">
# endif

```

**Comment by lipis** [comment]
Are you running the `gulp` command to initiate? Are there any errors maybe?

**Comment by lipis** [comment]
Closing due inactivity.. please report back if you still have an issue..
