### ISSUE TITLE
Using PyCharm Debugger

### ISSUE THREAD

**Issue by frannah** [gae-init/gae-init#795]
Hi 

Is there a way to run the application in gulp (as described in the documentation), and then use PyCharm's debugger to debug the web application?

I am having real trouble getting this to work (may just be old age or stupidity)

Help much appreciated!
frannah

**Comment by asmith26** [comment]
Hi @frannah 

The best way I've found running PyCharm's debugger with gae-init is via the following configuation:

![image](https://user-images.githubusercontent.com/6988036/34840642-890c140a-f6fd-11e7-9b8d-c8e6e36a4654.png)

Parameters: `/SOME PATH/gae-init/main --host 127.0.0.1 --port 8080 --admin_port 8081 --storage_path=/SOME PATH/gae-init/temp/storage --skip_sdk_update_check --log_level debug --clear_datastore False`

Hope this helps.

**Comment by lipis** [comment]
Basically the gulp command is just a wrapper for it.. [build.coffee#L36](https://github.com/gae-init/gae-init/blob/master/gulp/tasks/build.coffee#L36)

**Comment by lipis** [comment]
and in the [run.py#L339-L351](https://github.com/gae-init/gae-init/blob/master/run.py#L339-L351) :)

**Comment by frannah** [comment]
great - thanks.
