### ISSUE TITLE
Flask does not redirect to the canonical URL with the trailing slash on GAE

### ISSUE THREAD

**Issue by do-n-khanh** [gae-init/gae-init#878]
I am following the tutorial at http://docs.gae-init.appspot.com/tutorial/
On local host, Flask redirects to the canonical URL with the trailing slash. So if I visit localhost:8080/contact, it will take me to localhost:8080/contact/

However, when I deploy to google app engine, I try ***.appspot.com/contact, it just returns 404 error. It does not redirect to the canonical URL with the trailing slash. I really can not figure out the problem.

Another problem is that when I deloy to gae, it automatically become https://***.appspot.com.
I thought I have to follow this part to get https
http://docs.gae-init.appspot.com/howto/#letsencrypt

**Comment by lipis** [comment]
Can you provide the code for the contact handler?

As for the let's encrypt I think we can get rid of it right now, as you can simply do that with a click from App Engine console.

**Comment by do-n-khanh** [comment]
I exactly copy code for the contact handler from the tutorial. 
I try again everything, setup a new gae project, follow the tutorial again, and still get the same problem. 
can u try it?

import util

@app.route('/contact/')
@auth.login_required
def contact_list():
  contact_dbs, contact_cursor = model.Contact.get_dbs(
      user_key=auth.current_user_key(),
    )

  return flask.render_template(
      'contact_list.html',
      html_class='contact-list',
      title='Contact List',
      contact_dbs=contact_dbs,
      next_url=util.generate_next_url(contact_cursor),
    )

**Comment by lipis** [comment]
Well it works here: http://phonebook.gae-init.appspot.com/contact/ So I'm not sure what is wrong.. can you provide a link on where you deployed it?

**Comment by do-n-khanh** [comment]
Hi,
can u try here
does not work : https://ktest321986.appspot.com/contact

work : https://ktest321986.appspot.com/contact/

**Comment by do-n-khanh** [comment]
Hi lipis,

You can use below admin information to login to google cloud and check the code.
email : ktest3219@gmail.com
password: a12345bc

https://console.cloud.google.com/debug?project=ktest321986&authuser=1
