### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#882]
This is an issue to discuss how we should approach testing, particularly in light of the fact that we have Travis working now.

An approach using unittest is described here: [https://cloud.google.com/appengine/docs/standard/python/tools/localunittesting](https://cloud.google.com/appengine/docs/standard/python/tools/localunittesting) which seems like a reasonable approach -- although there are others based on nose - [NoseGAE](https://github.com/Trii/NoseGAE),  and [ferrisnose](https://github.com/theacodes/FerrisNose).

**Comment by mdxs** [comment]
Is this resolved with https://github.com/gae-init/gae-init/releases/tag/6.0.2 adding the [functional tests](https://github.com/gae-init/gae-init/pull/986)?

**Comment by rbubley** [comment]
Closed by #986
