### ISSUE TITLE
Downloading of static files

### ISSUE THREAD

**Issue by JamsheedMistri** [gae-init/gae-init#885]
Hi,

I'm trying to limit downloading of a specific file via flask. I'm putting the file I want to be downloaded in the `static` folder. Specifically, the file is `main/static/example/example.zip`. When making a request to `/module/download/example/`, it should be downloaded. Here is the code:
```@app.route('/module/download/<module_id>/')
def module_download(module_id):
  root_dir = os.path.dirname(os.getcwd())
  return flask.send_from_directory(os.path.join(root_dir, 'main', 'static', module_id), module_id + ".zip")
```

I get this (and a 404) when I try:
```
INFO     Sandbox prevented access to static file "PROJECT_DIR/main/static/example/example.zip"
```

Am I doing it right? If so, how do I prevent the error? If not, how can I do this better?

Thanks!

**Comment by pirroh** [comment]
It appears to be an issue with GAE rather than gae-init -- take a look at: https://groups.google.com/forum/#!topic/google-appengine/5VL7NJwvHec

**Comment by JamsheedMistri** [comment]
There is no `application_readable` property in `app.yaml`. If I add it and set `application_readable: true`, I get the following error:
```
google.appengine.api.yaml_errors.EventError: Unexpected attribute 'application_readable' for object of type AppInfoExternal.
```

**Comment by rbubley** [comment]
See <https://cloud.google.com/appengine/docs/standard/python/config/appref>

The `application_readable` element is a sub-element of handler.

**Comment by JamsheedMistri** [comment]
Thank you very much, this resolved my issue.
