### ISSUE TITLE
Add custom script to specific page

### ISSUE THREAD

**Issue by JamsheedMistri** [gae-init/gae-init#891]
Hi, [I already saw](http://docs.gae-init.appspot.com/howto/#add_scripts) that you can create custom scripts by adding them to `main/static/src/script`, however doing this adds them to all pages across the site — how can I only add a custom script to select pages?

**Comment by lipis** [comment]
You can do something like that: https://github.com/gae-init/gae-init/blob/master/main/static/src/script/site/app.coffee#L4

Where `html.auth` is the [`html_class`](https://github.com/gae-init/gae-init/blob/master/main/auth/auth.py#L228) that we are using by convention on every page..

**Comment by lipis** [comment]
Also there is no need to write in CoffeeScript you can simply add JS files instead..

**Comment by JamsheedMistri** [comment]
This makes a lot of sense, thanks!
