### ISSUE TITLE
Error when select more than 27 users to delete

### ISSUE THREAD

**Issue by do-n-khanh** [gae-init/gae-init#899]
When I select more than 27 users on http://localhost:3000/admin/user/?active=True&order=-modified to delete, I got below error from browser console

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
description
:
"Internal Server Error"
error_class
:
"BadRequestError"
error_code
:
500
error_message
:
"Internal Server Error"
error_name
:
"internal-server-error"
status
:
"error"

However, deleting less than 27 users is fine.

What is the problem? Is there any setting limitation here?
Thanks

**Comment by lipis** [comment]
Most likely time out.. after the refresh you might have less..

**Comment by do-n-khanh** [comment]
right, is there anyway to solve?

**Comment by lipis** [comment]
You will have to use Tasks API or something like that.. it was not in the scope for this project to overcomplicate things..
