### ISSUE TITLE
Feature request: include project id in deploy command

### ISSUE THREAD

**Issue by trickidicki** [gae-init/gae-init#920]
Would be great if the project id were included in build.coffee:

cmd: "#{dryrun}gcloud app deploy **--project {{project_id}}** main/app.yaml main/index.yaml#{options_str}"

Thanks!

**Comment by rbubley** [comment]
Would you like to submit a small PR? For a one-line change on this, you can use Github's online edit facility to do this.

**Comment by lipis** [comment]
I'm just not sure if it should be part of the core.. or per project.
