### ISSUE TITLE
gulp run fails with gcloud SDK 219.0.1

### ISSUE THREAD

**Issue by rbubley** [gae-init/gae-init#962]
This is an upstream issue with Google Cloud SDK 219.0.1

https://issuetracker.google.com/issues/117145272

Fix is to roll back to v. 218 or wait for the next release.

**Comment by lipis** [comment]
I had a similar issue

**Comment by mdxs** [comment]
Ditto

**Comment by lipis** [comment]
@rbubley is that related to the failing Travis CI tests?

**Comment by patrickmpoon** [comment]
I had some weird issues with v.220.0.0.  When running gulp, it would get to the "pip install -q -r reqs.txt" task and then consume all memory and froze my computer consistently.  I had to downgrade back to v.218.0.0 to get back to being functional.  To save time for some others:

`gcloud components update --version 218.0.0`

**Comment by lipis** [comment]
works now.. 221

**Comment by mdxs** [comment]
Don't think so... I believe that both 221 and 222 are still broken for our purposes; sticking to 218 using:
```
gcloud components update --version 218.0.0
# and testing within my project that the following works
gulp reset && yarn && gulp build
# on 219, 221 and 222 my virtual machine gets frozen... on 218 it works
```

**Comment by lipis** [comment]
works on my end

**Comment by mdxs** [comment]
I kept a Linux Task Manager running in my Xubuntu 18.04.1 Guest VM (using VMware 15.0.0 Pro on Windows 10) and noticed that a normal `yarn` (under 218) after a `gulp reset` shows some 232 to 250 processes at max; with some 50% of memory used at max.

However, when using 222 the same `yarn` on gae-init (after a `gulp reset`); goes 785+ processes, 95+% memory and 47% swap before it freezes; showing many `python -c import grpc` processes when the `pip install -q -r requirements.txt` part of a `yarn` command is running (after a `gulp reset`). At one point the swap goes to 91% with 1059 processes before it shows a `Killed` after the `pip install -q -r requirements.txt` and back to the prompt; but it suffers in recovering, is highly unresponsive and finally logs me out.

Now, I run my VM with just 1 CPU and 2 Gb of memory, so it might be that I can make it fail faster and better ;-)  Perhaps when you have more resources available, it doesn't show as an issue; but it feels like a runaway process/spawning to me in 219+.

**Comment by mdxs** [comment]
There is a comment in https://issuetracker.google.com/issues/117145272 that says:

> This also appears to be the cause of breaking any script that uses `dev_appserver.fix_sys_path()` 

Which is what gae-init does in run.py via the fix_path_cmd in the create_virtualenv() method.

The quoted comment also suggests a workaround:

> Workaround is to add `os.chdir(os.path.dirname(os.path.realpath(__file__)))` immediately below that line, probably can do a similar thing for the actual dev_appserver until this is fixed.

Which I may try at a later time to see if we can use that from within run.py to (temporarily) fix the issue. I'm however a little constrained in time, so it may take a while before I try.

**Comment by rbubley** [comment]
Maybe we can learn more if you manually break the install into stages, so, e.g. run

`gulp init` before running `yarn`.

If it fails at the `gulp init`, this can be broken down further (into `gulp pip` and `gulp
copy_bower_files`, etc.)

**Comment by rbubley** [comment]
Looking through the rest of the comments from @mxds’s link, it appears that running 

`pip install grpcio`

may fix it.

**Comment by mdxs** [comment]
Okay, I tried with GAE SDK 225 and experience similar issues that I noted in the 219-222 versions of the SDK. I made some screenshots that I shared on the general Slack channel for gae-init. Compared to the SDK 218 screenshot, you can clearly see far more processes, memory, and swap usage with SDK 225 when using a `gulp reset`, `yarn` sequence. The [suggestion](https://github.com/gae-init/gae-init/issues/962#issuecomment-439330104) to put `gulp init` before `yarn` was tried, but fails as I only get `gulp` with `yarn` in that sequence (as shown in screenshots).

**Comment by mdxs** [comment]
The merge of #1015 should resolve this issue and you should be able to use the latest SDK.
