### ISSUE TITLE
Update requirements in Pageres section of Test page

### ISSUE THREAD

**Issue by mdxs** [gae-init/gae-init#983]
Should this be updated to use yarn nowadays?
https://github.com/gae-init/gae-init/blob/c9b7d6442c95acf208e26fbb829d6b29a9b9e8a9/main/templates/admin/test/test_pageres.html#L4

and would that possibly be `yarn global add pageres-cli`?

**Comment by lipis** [comment]
I would say yes.. even though I doubt that anyone was using it :)

**Comment by mdxs** [comment]
The PR #993 supersedes #992 (which incorrectly showed some extra dependencies bumps).
